### ISSUE TITLE
sbJSON Community and Organization tags

### ISSUE THREAD

**Issue by jlblcc** [adiwg/mdTranslator#100]
We'll need to create community and organization tags when translating to sbJSON. Can possibly capture from citation or a custom keyword thesaurus.

See example here: https://www.sciencebase.gov/catalog/item/593eed53e4b0764e6c61bb43?format=json

**Comment by jlblcc** [comment]
SB Vocabs: 

https://www.sciencebase.gov/vocab/categories?parentId=51424b20e4b019a2e6022a14
https://www.sciencebase.gov/vocab/vocabulary/51424afae4b019a2e6022a11

**Comment by hmaier-fws** [comment]
Current stakeholders can not identify a need for this feature.
