### ISSUE TITLE
fgdc Larger Work Citation

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdTranslator#108]
**Larger work citation** is embedded in citation and I have mapping this to *associatedResource*.  However, associated resource requires a *resourceType* which is not available in FGDC.  I can default the resource type to:

- [x] leave blank ... in which case the mdJson will not be valid.  This will force the user to fix it in the editor
- [ ] default to 'missing' ... in which case the mdJson will pass, and the user may forget to fix it
- [ ] default to 'project' ... which is the most likely case, but because the entry is valid the user may forget to review it.

Cast your vote

**Comment by dwalt** [comment]
We use larger work citation for citing a project for about 90% of our records. However others use if for other purposes, such as, to cite a collaborative initiative. There is a contingent within USGS that is using it to cite a "primary" publication with a move to make it policy so it will play well in Science Data Catalog. In fact OME is enforcing this.

**Comment by stansmith907** [comment]
I believe we should stay true to the FGDC standard and corrupt the meaning of elements.  So I don't see that we would ever turn larger work citation into a publication.

**Comment by dwalt** [comment]
I would agree.

**Comment by jlblcc** [comment]
:+1:
