### ISSUE TITLE
fgdc Contact Name with ORCID

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdTranslator#109]
The Alaska Science Center's practice of is attaching ORCID to contact name raises a few issues:
 * If a contact is to be reused elsewhere in the metadata record it must always have the same name, e.i. have the ORCID attached and in the same format.  Because FGDC does not support contact IDs I must match contacts by contact name.  Any variation in name will result in a new contact. 
* ORCID is being attached to the name because it is deemed important.  However, I probably should not try and pluck it from the name field to create a contact identifier since this is not a universal or wise convention to attach supportive information to the name field. If we want to preserve ORCID we should find another method.

**Comment by dwalt** [comment]
I don't know of any other way to record ORCIDs in FGDC. We would not continue this practice in ISO. I think it is perfectly fine to leave the ORCID attached to the name as contact name. We use ORCID consistently, but this is not a universal practice in USGS. They are trappable within a string by the use of parenthesis to encapsulate the id.

**Comment by stansmith907** [comment]
I'm okay with ASC to using the name field as they wish.  But do not plan to scan it for ORCID as the FGDC reader is for a broad audience and will try to stay true to the standard.
