### ISSUE TITLE
fgdc Handling DateTime

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdTranslator#110]
The FGDC format for date is YYYYMMDD and for ISO YYYY-MM-DD.  The FGDC format for time is hh:mm:ss and for ISO hh:mm:ss.s+hh:mm.  See [CIESIN](http://sedac.ciesin.columbia.edu/metadata/guide/guide_toc.html FGDC) documentation. FGDC also delivers date and time in separate elements these must be reconnected for mdEditor, mdTranslator, and ISO.  Most of this translation is straight forward.  However, handling of timezones needs some explaination.

FGDC does not provide offset with time format, nor is timezone or offset available elsewhere in the FGDC record.  What FGDC does have in section 7 (metadata information) is 'time convention' for the metadata record.  Time convention is a text domain of ['universal time', 'local time', 'local time with time differential factor'].  Since the 'differential factor' is not specified I consider that enumeration the same as local time.  

 * if the time convention is 'universal time' I attach +00:00 to the time and convert that to a dateTime object
 * when the time convention is 'local time' 
    * I find the local offset in seconds from UTC
    * convert the offset to hours and minutes
    * attach the offset and convert that to a dateTime object
    * refactor the dateTime object to universal time

What is implied here is that all dateTime objects are stored in mdTranslator as UTC.  This works nicely for times entered in 'universal time'.  However there are issues when 'local time' is used.  Here are the issues I see:
1. The offset time offset will be computed by the mdTranslator server, wherever it may be.
2. Time offset will be inconsistent depending on the season, standard time vs. daylight savings time.
3. mdEditor does the same thing (saved UTC, displays local).  If the translator and editor sit in different timezones, times shown in the editor will differ from times entered in the FGDC record.  However the saved time values will be the same.  
4. It seems best to enter all times in FGDC records as UTC.  However, I don't think there is a way to enter UTC times using the mdEditor.

If the 'time convention' was not set in FGDC I am defaulting it to local time.  

I think the best solution is to avoid time altogether unless it is critical, then use universal time in FGDC and local time in the mdEditor.  Please advise if you see a better solution.

**Comment by dwalt** [comment]
This is how Metavist writes it out:
<pubdate>20170203</pubdate>
<pubtime>103146</pubtime>
Verifying what you said, time zone or offset are not recorded. If we use time, which is rare, we would likely use local time.

**Comment by stansmith907** [comment]
Okay, I'll add translation of time in nnnnnn format to the date/time routine.
