### ISSUE TITLE
fgdc Citation Publication Info

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdTranslator#111]
FGDC *citation* has a publication information section (*pubinfo*) which only has elements for place of publication (*pubplace*) and publisher (*publish*).  As these are the only two elements I assume they are only used when the citation is for a publication.  Is this ...
- [ ] true
- [ ] false

Other than the existence of *pubinfo* how do I know if the citation is for a publication?  

As there are no corresponding items in mdJson, what do we propose to do with this info?
- [x] Follow NOAA's FGDC to ISO mapping.
   * make a mdTranslator *contact* for *publish* with type = 'organization'; 
   * add *pubplace* to the address description element of *contact*; 
   * add a *responsibleParty* record to the *citation* with *roleName* of 'publisher'. 
- [ ] add a resource type of 'publication' if present
- [ ] move data to citation.otherCitationDetails.  Information will be lost if writer format chosen is FGDC
- [ ] drop information if citation is not for a publication.

**Comment by dwalt** [comment]
Maybe. We uses these fields in Primary Citation to indicate the data set is being "published" by the Alaska Science Center. We put publications in cross reference section. As mentioned in the Larger Work Citation issue, a large faction in USGS is using Larger Work Citation for a publication. Further, we may have publication references embedded in Methods and Process Steps. I think you can assume usage of these fields indicates who the publisher is for the resource, but not assume it is a publication. We use Data Presentation Form domain value of "journal article" to explicitly identify a publication citation.

**Comment by stansmith907** [comment]
The shortcomings of FGDC support for publications becoming evident in these issue threads.  Cross reference (*crossref*) is for other datasets as per its definition in FGDC documentation: "Cross Reference -- information about other, related data sets that are likely to be of interest."  In the reading process *crossref* will end up in *associatedResource* which is a good place for journal articles.  Much preferable to *largerWorkCitation*.
