### ISSUE TITLE
fgdc Contact Type

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdTranslator#112]
All contacts will be entered as 'individual' as there is no way to distinguish between individuals and organizations in FGDC that I can see.  Any ideas?

**Comment by dwalt** [comment]
origin tags could probably be assumed person as it is intended to be an
author list. That is not a guarantee of how it was used  of coarse. cntorgp
 tag found in distributor, contact, metadata author, etc. is explicitly for
organization and would be reliable.

**Comment by stansmith907** [comment]
Noted.  Thanks Dennis, I had only been working through Citation at this point.  I will ingest the other tags you mentioned as 'organizations'.  But, *citation* will only generate 'individual' contacts.

**Comment by dwalt** [comment]
Didn't take long to find an exception for origin:

      <srcinfo>
        <srccite>
          <citeinfo>
            <origin>Intermap Technologies</origin>
            <pubdate>2012</pubdate>
            <title>Primary IfSAR Dataset</title>
            <geoform>remote-sensing image</geoform>
          </citeinfo>
        </srccite>

Here is an example in which a person is named for contact:

      <cntinfo>
        <cntperp>
          <cntper>Mayumi Arimitsu</cntper>
          <cntorg>U.S. Geological Survey, Alaska Science Center</cntorg>
        </cntperp>

Here is an example in which an organization is named for contact:

    <cntinfo>
        <cntorgp>
          <cntorg>U.S. Geological Survey, Alaska Science Center</cntorg>
        </cntorgp>
