### ISSUE TITLE
fgdc bio Spatial Domain geographic description

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdTranslator#115]
The FGDC examples from ASC have a geographic description (*descgeog*) tag inside the spatial domain (*spdom*) section.  I don't see this in the FGDC documentation.  Is this a local profile?  Or is this a legitimate FGDC element I missed?  

Also, do you have any example metadata with spatial domains defined using geographic polygons (*dsgpolyo*) in stead of or in addition to a bounding box?

**Comment by stansmith907** [comment]
I think I answered my own question. The geographic description tag is not part of CSGDM 1993. This was added to the data identification section via the 1999 Biological extension set.  A quick review of the 1999 documentation shows extensions were added to nearly all existing 1993 sections.  Great!  Just what I needed, another 58 pages of FGDC Standard to incorporate into the reader.  I think I'll work through the 1993 standard then go back and add the extension elements from the 1999 biological extension.

**Comment by dwalt** [comment]
Interesting, I did not know it was part of the biological extension. The
tool most here use, Metavist, includes the extension, but does not identify
which elements are part of the extension. We have found a useful field to
generally describe location, where coordinates mean little without a
geospatial viewer.

Also interesting that the standard integrated the extensions. That would
mean shoreline and remote sensing elements would be fairplay. The problem
with this is these elements may be used without declaring the metadata
record extension. For instance, in some cases CSDGM may be declared, yet
the geographic description or methods is used.

**Comment by stansmith907** [comment]
I have not seen any evidence of an extension other than the Biological Extension in any of the sample FGDC metadata you sent me.  So, I presume it's the only extension incorporated into Metavist.  That said...

Definition *descgeog*: "Description of geographic extent. Short description of the geographic areal domain of the data set. Examples include, "Manistee River watershed", ..."

Here are a few choices for handling this element in mdJson/mdTranslator:
 - [ ] create a new extent and place in extent.description
 - [ ] add a *description* element to *geographicExtent* to hold this value.  Also note that both *temporalExtent* and *verticalExtent* already have a *description* element.
 - [ ] ignore element

**Comment by stansmith907** [comment]
Schema rules for geographicExtent.description:

 - [x] string
 - [x] optional

**Comment by dwalt** [comment]
The description is co-located in Metavist with the bounding box, implying
the description being general in intent and in association with the
bounding box. I would vote to add a description to geographicExtent.
