### ISSUE TITLE
fgdc time periods - 'Unknown'

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdTranslator#124]
I see instances of dates and time periods in the FGDC examples with the value 'Unknown'.  Is this an acceptable value written by Metavist when a required date is not known?  Let me know, if so I'll need to trap it.  I can't find a discussion of this in the FGDC documentation. 

 - [ ] 'Unknown' is valid FGDC date value.
 - [ ] not valid FGDC.

**Comment by dwalt** [comment]
The domain is:
"Unknown""Unpublished material"free date

**Comment by stansmith907** [comment]
So it is.  Thanks.  Back to the drawing board.

I'll trap these strange entries in the translations.  
 * *Unknown* - Since there is no way to store a date of "Unknown", and unknown is essentially the same as no-date-at-all, I'll skip these entries.  I suppose on writing FGDC missing date can be output as 'Unknown'.
 * *Unpublished material* - This information describes the resource status and not the date.  I'll likely follow NOAA's lead and drop it.

**Comment by dwalt** [comment]
Sounds reasonable. I have not seen unpublished material used.

**Comment by stansmith907** [comment]
Looks like FGDC uses this method to subvert a required field.  It is at least a declaration that it is unknown rather than overlooked.
