### ISSUE TITLE
Too many identifiers created when reading itemLinks from ScienceBase

### ISSUE THREAD

**Issue by jlblcc** [adiwg/mdTranslator#126]
We should only keep the identifier for the __related__ resource when translating. Otherwise it's not possible to determine which id is actually for the related resource.

**Comment by stansmith907** [comment]
I thought we decided to keep all related item ids and set their type in *identifier.description*.  Is this incorrect?  

Also, if we drop all but one identifier which ID from the *relatedItem* retch do we keep?  
 - [ ] 'id'
 - [ ] 'itemId'
 - [ ] 'relatedItemId' if forward and 'itemId' if reverse

And regardless of the ID's source we name this identifier 'ScienceBase itemId'?

**Comment by jlblcc** [comment]
I'm sure you're right and we did agree to that. I just didn't realize the
problem until just now. When we send the record to SB, it uses
associatedResource to create item links by scanning the identifiers. That
means it expects the identifier for the *associated resource*. The rest of
the identifiers are not needed and might actually cause bad itemLinks to be
generated. At least, that's my current understanding...

**Comment by stansmith907** [comment]
And I suspect there is even more to learn about ScienceBase as time go by.  

I'll wait to hear back from you, but from your comment I am assuming you are referring to how ScienceBase harvests mdJson records since *associated resource*(s) are not written by the sbJson writer.  And the ID to be saved is the third option in my above comment.  

> - [ ] 'id'
> - [ ] 'itemId'
> - [ ] 'relatedItemId' if forward and 'itemId' if reverse

**Comment by jlblcc** [comment]
Yes the id to be written is dependent on the direction of the relationship. We should drop the other ids, or put them in description.

**Comment by stansmith907** [comment]
Done.  I set the description of the identifier as 'relatedItemId'
