### ISSUE TITLE
fgdc entity-attribute information not supported by mdJson/mdTranslator

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdTranslator#129]
Working though the FGDC entity-attribute section (5) I found much of the information not supported by our mdTranslator and mdJson schemas.  This is likely because we patterned mdTranslator *dataDictionary* on SQL table creation requirements.  Also, ISO implements data dictionaries using FC_FeatureCatalogue which optimistically is a poor fit.  

FGDC has additional fields that could enrich our description of entities and attributes that we may wish to adopt even if we can only move a few of them to ISO metadata records.  If all these fields were added we could accurately describe ASCII CSV or tabular datasets in addition to SQL and spreadsheets.  

 - [ ] attribute definition external reference (is in FC_FeatureCatalogue)
 - [ ] attribute unit measurement resolution
 - [ ] attribute measurement frequency
 - [ ] attribute {begin date / end date}n
 - [ ] attribute accuracy (likely in ISO 19157)
 - [ ] case sensitive (Boolean)
 - [ ] field width
and others that could be added to entity
 - [ ] entity definition external reference (is in FC_FeatureCatalogue)
 - [ ] missing value code
 - [ ] field separation character
 - [ ] number of header lines 
 - [ ] quote character [ single | double ]
and others that could be added to domain
 - [ ] domain definition external reference (is in FC_FeatureCatalogue)
 - [ ] unrepresentable domain (text description)

**Comment by dwalt** [comment]
Of those, unrepresentable domain is used quite a bit.. External references
are used occasionally in terms of citing the source. The rest I have not
seen used. ISO made a confusing mess out of data dictionary, IMO.
