### ISSUE TITLE
fgdc entity-attribute multiple domain definitions

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdTranslator#130]
Maybe I'm reading the FGDC standard incorrectly, but it appears that an attribute can be assigned multiple domains.  In part this is because there are four domain types [ enumerated | range | codeset | unrepresentable ].  

I understand that multiple *range* domains may be needed to accurately describe ranges of acceptable values in an attribute.  In mdTranslator/mdJson I maped these to minValue and maxValue of the attribute, but we allow only one set of min-max.

However, I can't see a reason for an attribute to have multiple *enumerated*, *codeset*, or *unrepresentable* domains.  Or that more than one of these domain types should be declared simultaneously. Dennis, can you verify this in Metavist? 

Presently mdTranslator will only handle a single *enumerated* and single *range* domain for an attribute.  And we have not implemented the other two domain types.

**Comment by dwalt** [comment]
Yes, you can have multiple domains of same or different types. An example
of this usage is a range domain for numerical values, then have an
additional domain to cover special meaning character codes.

A lot of domains will be lost from FGDC if these other domain types are not
supported and could be a show stopper for acceptance.

**Comment by stansmith907** [comment]
Thanks for checking this out.  

Your explanation illustrates an attribute with a single range and a single enumerated domain but not multiple definitions of each domain type.  We do cover your example now in mdJson/mdTranslator/ISO.  I'm interested in knowing if you ever document any of the following scenarios:
 - [ ] an attribute with multiple range domains
 - [ ] an attribute with an unrepresentable domain declared
 - [ ] an attribute with multiple enumerated domains
 - [ ] an attribute with a codeset domain
 - [ ] an attribute with multiple codeset domains
 - [ ] an attribute with both a enumerated and codeset domain
 - [ ] none of the above

Check all that apply, and/or comment back on any unusual scenario I missed.
Thanks

**Comment by dwalt** [comment]
- [x]  an attribute with multiple range domains
- [x] an attribute with an unrepresentable domain declared
- [ ] an attribute with multiple unrepresentable domains
- [ ] an attribute with multiple enumerated domains
- [x] an attribute with a codeset domain
- [ ] an attribute with multiple codeset domains
- [ ] an attribute with both a enumerated and codeset domains
- [ ] none of the above

**Comment by stansmith907** [comment]
New insight into FGDC domains!  After getting farther into the translation process I now see that enumerated domains are not grouped.  This essentially means that all enumerated values belong to the same domain no matter how they are grouped.  So, only one enumerated domains is possible.  

However it is still possible that an enumerated domain may also be documented by an external codeset or multiple codesets.  I have removed 'multiple enumerated domains' from the list of considerations.

**Comment by stansmith907** [comment]
Thanks Dennis, next week we should discuss which, if any, of these options we should move into mdTranslator/mdJson/mdEditor.
