### ISSUE TITLE
fgdc entity-attribute section

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdTranslator#132]
In the FGDC documentation the *entity* tag (short name) is <enttype> - see the documentation page image below.  In all the files Dennis has sent me which were prepared by Metavist <enttyp> is used (without the 'e').  I have changed all my example files to match the FGDC documentation.  

Let me know if I've missed something.

![image](https://user-images.githubusercontent.com/4998910/30303793-a0d17130-9716-11e7-9338-fa6de61a9803.png)

**Comment by dwalt** [comment]
Interesting. These records have all passed metadata parser without
incident. Maybe a change in the standard?

**Comment by stansmith907** [comment]
I changed the fgdc reader to search both *enttype* and *enttyp*.  Hope this is satisfactory.
