### ISSUE TITLE
nil error in HTML writer (allocation)

### ISSUE THREAD

**Issue by jlblcc** [adiwg/mdTranslator#135]
Got an error in the HTML writer in the allocation section. Looks like it might be [choking on non-existent contact ids](https://github.com/adiwg/mdTranslator/blob/master/lib/adiwg/mdtranslator/writers/html/sections/html_allocation.rb#L51)? Probably should capture those errors. This is a different use of contact ids outside of the responsible party - probably why the error isn't trapped.

```
.rvm/gems/ruby-2.3.3/gems/adiwg-mdtranslator-2.3.0/lib/adiwg/mdtranslator/writers/html/sections/html_allocation.rb:51:in `+': no implicit conversion of nil into String (TypeError)
```

**Comment by stansmith907** [comment]
I added a trap for instances where the source or recipient IDs are not found in the contact array.  The HTML how displays 'Contact {...} not found!'

In general, this level of testing is not done in the HTML writer.  It's too difficult to interrogate the HTML output.
