### ISSUE TITLE
Allow mutiple taxonomic definitions

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdTranslator#14]
I just discovered it is possible (and desirable) to have multiple taxonomic definitions in the taxononic section of ISO metadata.  The taxonomy hierarchy can repetitively branch at any level with each branch able to continue toward species or branch again within itself.  Applying this patch will require changes to mdJson, the internal object, mdTranslator readers and writers, and json-schema-viewer.  What a mess!

**Comment by jlblcc** [comment]
Should we handle this in v1.1?

**Comment by stansmith907** [comment]
The feature should be supported the initial mdEditor release.  So I suppose it depends on when v1.1 would be released.

**Comment by jlblcc** [comment]
So is all the branching done within "taxonClass"? Do we really need to support branching within branches? Wouldn't it be enough to make taxonClass and array of taxonclass arrays:

```json
 "taxonClass": [
  [
    {
      "common": "Sea Otter",
      "taxonRank": "Species",
      "taxonValue": "Enhydra lutris"
    },
    {
      "common": "Southern Sea Otter",
      "taxonRank": "Subspecies",
      "taxonValue": "Enhydra"
    }
  ]
]
```
I see the logic of branching, I just don't thinking the expense of implementing it would be justified. I also don't imagine it would be practical to implement this when constructing mdJson. I don't store the entire taxonomic hierarchy I only store the TSN of the lowest level. So, when constructing the mdJSON it's actually much easier to just output the entire taxonomic tree for each species rather than trying to figure out where the branches are so they fit into one object.

**Comment by stansmith907** [comment]
Not sure I follow your example.  The example is not a split but a continuation of the hierarchy chain from rank Species to rand Subspecies.  The example I have in front of me was built in MetaVist.  It runs 13 pages of taxonomy with multiple splits of Order, Family, Genus, and surprisingly few of Species.  It is not the only project here that scientists are claiming the need for multiple species recorded in the metadata.

**Comment by jlblcc** [comment]
I agree with the need for multiple species. I just don't see the need for the branching. It's simpler to just list multiple taxonomies.

Here's the example with two taxonomies:

```json
 "taxonClass": [
  [
    {
      "common": "Sea Otter",
      "taxonRank": "Species",
      "taxonValue": "Enhydra lutris"
    },
    {
      "common": "Southern Sea Otter",
      "taxonRank": "Subspecies",
      "taxonValue": "Enhydra"
    }
  ],
  [
    {
      "common": "Fairy Otter",
      "taxonRank": "Species",
      "taxonValue": "Enhydra fairis"
    },
    {
      "common": "Southern Fairy Otter",
      "taxonRank": "Subspecies",
      "taxonValue": "Enhydra fairis inferus"
    }
  ]
]
```

**Comment by stansmith907** [comment]
So would list the entire 12 or 13 levels for each species array defined?

**Comment by jlblcc** [comment]
Yeah. Somewhat redundant, but it would be easy to generate from a database if you're using ITIS.

**Comment by stansmith907** [comment]
It would be easier throughout the entire process, but verbose.  Not sure that would be best for the mdEditor.

**Comment by jlblcc** [comment]
Are we required to include the entire taxonomy for ISO?

**Comment by dwalt** [comment]
Sorry, I had watch turned off for my holiday break. So Josh, your example only shows the atomic level. Are you advocating creating the entire hierarchy for each species listed, in JSON?

**Comment by jlblcc** [comment]
Yes. It's more verbose, but way easier to deal with programmatically.

**Comment by dwalt** [comment]
Yeah, that is easier, multi-level input would be a nightmare to parse. Creating it from a database would be easy, but anyone hand building their JSON will swear.

I'm wondering what the ISO output will look like. We also should consider the output format for the HTML writer.

**Comment by jlblcc** [comment]
>anyone hand building their JSON will swear

No "buts", they will be swearing regardless!

**Comment by dwalt** [comment]
Ha! Probably right!

**Comment by stansmith907** [comment]
I just spent some time with the ISO 19115-2 XSDs.  I find the taxonomy > MD_TaxonSys section will support only a single taxonCI section which means we can have only a single top node (Kingdom).  After that we can branch because a taxonCl element can have many taxonCl elements within itself. 

````xml
 <gmd:taxonomy>
	<gmd:MD_TaxonSys>
	   <gmd:taxonCl>
		  <gmd:MD_TaxonCl>
			 <gmd:common/>
			 <gmd:taxonrn>
				<gco:CharacterString>Kingdom</gco:CharacterString>
			 </gmd:taxonrn>
			 <gmd:taxonrv>
				<gco:CharacterString>Animalia</gco:CharacterString>
			 </gmd:taxonrv>
			 <gmd:taxonCl>
				 <gmd:MD_TaxonCl>
						<gmd:taxonrn>
							<gco:CharacterString>Phylum</gco:CharacterString>
						</gmd:taxonrn>
						<gmd:taxonrv>
							<gco:CharacterString>Chordata</gco:CharacterString>
						</gmd:taxonrv>
						<gmd:taxonCl>
							<gmd:MD_TaxonCl>
								<gmd:taxonrn>
									<gco:CharacterString>Subphylum</gco:CharacterString>
								</gmd:taxonrn>
								<gmd:taxonrv>
									<gco:CharacterString>Subphylum</gco:CharacterString>
								</gmd:taxonrv>
							</gmd:MD_TaxonCl>
						</gmd:taxonCl>
					</gmd:MD_TaxonCl> 
			 </gmd:taxonCl>
			 <gmd:taxonCl>
				<gmd:MD_TaxonCl>
				   <gmd:common/>
				   <gmd:taxonrn>
					  <gco:CharacterString>Phylum</gco:CharacterString>
				   </gmd:taxonrn>
				   <gmd:taxonrv>
					  <gco:CharacterString>Chordata</gco:CharacterString>
				   </gmd:taxonrv>
				   <gmd:taxonCl>
					  <gmd:MD_TaxonCl>
						 <gmd:common/>
						 <gmd:taxonrn>
							<gco:CharacterString>Subphylum</gco:CharacterString>
						 </gmd:taxonrn>
						 <gmd:taxonrv>
							<gco:CharacterString>Subphylum</gco:CharacterString>
						 </gmd:taxonrv>
						 <gmd:taxonCl>
							<gmd:MD_TaxonCl>
							   <gmd:common/>
							   <gmd:taxonrn>
````

I'm thinking we take the simple approach for mdJson and create an array of full taxonomic structures.  I would also keep the full structures within the internal object and then let the writer manage it's peculiar requirements for its standard.

Thoughts?

**Comment by stansmith907** [comment]
Changed `taxonomy` from object to array.
