### ISSUE TITLE
fgdc bio lineage methodology

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdTranslator#142]
The *method* tag is a Biological extension to the data quality section of the FGDC standard.
Definition *method*: "Information about a single step of field and/or laboratory work."

````xml
      <method>
        <methtype>Field</methtype>
        <methodid>
          <methkt>methodology keyword thesaurus</methkt>
          <methkey>methodology keyword 1</methkey>
          <methkey>methodology keyword 2</methkey>
        </methodid>
        <methdesc>We captured brant by herding</methdesc>
        <methcite>
          <citeinfo>
            <origin>National Environmental Methods Index</origin>
            <pubdate>Unknown</pubdate>
            <title>NEMI</title>
            <geoform>database</geoform>
          </citeinfo>
        </methcite>
        <methcite>{methodology_citation}</citeinfo>
        </methcite>
      </method>
````

I would like to push these methodology citations into lineage.processStep.citation in mdJson/mdTranslator.   The FGDC process steps do not include citations so this seems like a good move.  However, it's uncertain now method steps relate to process steps if both are defined; or if there is an order to the method steps.  I assume we would assign each method to a separate process step with consideration of order. 

 - [x] ingest the methodology as a separate process step
 - [ ] ignore methodology

The keyword section of methodology is easily moved to keywords and assigned a *keywordType* = 'method'.  However, in the fgdc writer I would not be able to return them to the same *method* object pared with their method citation without using the keywordObject.id.  What to do?

 - [ ] don't worry about putting the keywords back with the proper citation
 - [ ] modify mdJson/mdTranslator to keep the association
 - [x] ignore method keywords

**Comment by dwalt** [comment]
I would vote to implement methods in lineage/process steps.

**Comment by dwalt** [comment]
Updated issue to assert putting methods into process steps as individual processes. Include the method citation.

Ignore method keywords. No known usage. Throws errors if not provided regardless if content is not biological. Requirement is invalid for Standard CSDGM as method keywords are not recognized.

**Comment by jwaspin** [comment]
Move methodology from lineage->citation to lineage->processStep

methodDesc goes into processStep->description

citation goes into processStep->reference[]

csdgm writer: relax keywords requirement
