### ISSUE TITLE
fgdc bio ASCII file format

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdTranslator#143]
The FGDC Biological extension provides for a description of ASCII file layout within the distribution.standardOrder.digitalForm.digitalInformation section. 

I have added these field to issue #129 entity attribute description rather than the distribution process.  

 - [ ] add ASCII descriptions to distribution process
 - [ ] consider ASCII description in entity attribute section
 - [ ] ignore

````xml
          <asciistr>
            <recdel>\n</recdel>
            <numheadl>1</numheadl>
            <deschead>column names</deschead>
            <orienta>columnmajor</orienta>
            <casesens>N</casesens>
            <authent>12ad155ee845d5c4</authent>
            <quotech>"'"</quotech>
            <datafiel>
              <dfieldnm>field1</dfieldnm>
              <missingv>-1</missingv>
              <dfwidth>12</dfwidth>
            </datafiel>
            <datafiel>
              <dfieldnm>field2</dfieldnm>
              <missingv>-1</missingv>
              <dfwidthd>;</dfwidthd>
            </datafiel>
          </asciistr>
````

**Comment by dwalt** [comment]
I can't say I have ever used this. I have seen an obscure data type
instance or two that this could be applied to.
