### ISSUE TITLE
sbJson reader execution fail tests

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdTranslator#146]
Some sbJson input is failing due to tests in the sbJson reader.  These are the current tests.  We should decide which should remain in the code.

 - [ ] contact.contactName missing
 - [ ] contact.contactType missing
 - [ ] contact.contactType not [ 'person' | 'organization' ]
 - [ ] weblink.uri missing
 - [ ] weblink.type missing Note: weblinks of type = 'browseImage' are placed in browseGraphic objects, all others are placed in additionalDocument.citation.onlineResource objects.  
 - [x] weblink.type missing Alternative: place all non-browseImage weblink types, including nil in additional documents.

**Comment by dwalt** [comment]
What is contact type and weblink type?

**Comment by stansmith907** [comment]
If contact name missing - drop contact record
If contact type missing default to person
If weblink uri missing - drop it
