### ISSUE TITLE
Modify parameter order on translate

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdTranslator#15]
The current parameter order for translate is (file, reader, writer, validation level, show empty). 

The issue is validation applies to the reader, but the writer parameter is in between.  That makes it awkward to specify a validation level when no writer is needed.  Ruby does not allow the following syntax translator(file, reader,, validation level) even when a default value for the missing parameter is defined.  

If I move the parameters around to translate(file, reader, validation level, writer, show empty) I think translate(file, reader, validation level) will pass for polymorphism.  

This should not effect the CLI or API as these are both named parameter driven.  

What you think?

**Comment by jlblcc** [comment]
Another (better?) option would be to use an options hash or keyword arguments(Ruby 2.0+) to pass in variables. See http://robots.thoughtbot.com/ruby-2-keyword-arguments for a write up.

**Comment by stansmith907** [comment]
I kind of like that.  Good find, but will have to push out new mdTranslator and mdTranslator-rails code.  And you will need to modify your project metadata app.

**Comment by jlblcc** [comment]
Shouldn't affect the CLI, right? That's how I call the translator from the PTS.

**Comment by stansmith907** [comment]
We will see if I can even use keyword arguments.  I'm just getting back to the office to play with it, but early tests suggests that creating keyword arguments has much the same consequence as creating global variables.  Any routine that has a call to a method using keyword arguments must reserve those names for the method call.  This could be dangerous, or maybe I'm using it wrong.  Need to play with it some more to be sure.

**Comment by stansmith907** [comment]
After some playing it appears the problem seems to be with the IDE.  It's real-time syntax checker cannot isolate the keyword parameter names when the method is defined in another namespace.  But it works properly in same namespace.  But that's not a real problem.  Back to playing.

**Comment by stansmith907** [comment]
This the method definition and call format I have been playing with.  Are we all ok with this?  I'll push it out tomorrow if ok.  

````ruby
def self.translate(file:, reader:, validate: 'normal', writer: nil, showAllTags: false)

ADIWG::Mdtranslator.translate(file: jsonObj, reader: 'mdJson', validate: 'normal', writer: 'iso19115_2', showAllTags: 'true') 
````

**Comment by stansmith907** [comment]
Implemented as above.  Bumped version 0.12.0
