### ISSUE TITLE
Harvest Set tag for sbJSON should include the title only

### ISSUE THREAD

**Issue by jlblcc** [adiwg/mdTranslator#150]
We shouldn't concatenate the repository name in the value for the "name". See: https://github.com/adiwg/mdTranslator/blob/master/lib/adiwg/mdtranslator/writers/sbJson/sections/sbJson_tag.rb#L70

Just include the title.

**Comment by stansmith907** [comment]
Okay.  However, repository name is required while citation.title is not.  Therefore, if citation.title is missing I will drop the tag.

**Comment by jlblcc** [comment]
:+1: Main thing is to allow users full control of tag name in the sbJSON output.
