### ISSUE TITLE
Error in html writer when topologyLevel is null

### ISSUE THREAD

**Issue by jlblcc** [adiwg/mdTranslator#152]
Just need to check topologyLevel before running `text!`. Problem mainly when translating from FGDC.
See: https://github.com/adiwg/mdTranslator/blob/master/lib/adiwg/mdtranslator/writers/html/sections/html_vectorRepresentation.rb#L27

Since this seems to be an  on-going issue, I'm wondering if we shouldn't extend Builder::XmlMarkup with a `textIf!` method that checks for a null value before calling `text!`?

**Comment by jlblcc** [comment]
[Example XML that fails](https://www.sciencebase.gov/catalog/file/get/58b47870e4b01ccd54fca8d0?f=__disk__58%2Fb7%2F40%2F58b74049b0b1484cd1376372ffc27518804023e7)

**Comment by stansmith907** [comment]
I reviewed all 80+ html writer modules and found a few more instances of writes not testing for nil values.  Most were required fields such as a keywordObject with no keyword, but set checks around these anyway.  The only exception is contactId.  contactId is used in creating hyperlinks within the html document thus a nil contactId is going to create problems beyond just a crashing text field.
