### ISSUE TITLE
mdJSON reader version is stale

### ISSUE THREAD

**Issue by jlblcc** [adiwg/mdTranslator#158]
The mdJSON [reader version is out of date (2.2.0)](https://github.com/adiwg/mdTranslator/blob/master/lib/adiwg/mdtranslator/readers/mdJson/version.rb). It fails with the current version of mdJSON(2.3.2).

Might be a good idea to write a test that compares to the schema version in the [gemspec](https://github.com/adiwg/mdTranslator/blob/master/adiwg-mdtranslator.gemspec#L36).

**Comment by stansmith907** [comment]
True, I should have updated the mdJson reader version.  But the version number being out of sync with the schema should not cause a failure, the reader version is comment only - the reader is not loaded external to the entire mdTranslator. 

The two version numbers cannot be synced either.  The mdJson reader version will naturally be ahead of the schema version.  The test should verify the reader version is greater than to equal the schema version. 

That said, what's failing?  And am I missing something?

**Comment by jlblcc** [comment]
It was failing for me when reading mdJSON, version set to 2.3.2

**Comment by stansmith907** [comment]
Can you be more specific?  I have 37 places I have had to step around schema validation because the schema does allow the new fields recently added.  Also, I just made a domainItems optional rather than required.  I didn't think any of these would impact older mdJson, but maybe!  

Are all your jobs failing?  Or just one?

**Comment by jlblcc** [comment]
I get a `readerStructureMessage: mdJson schema version '2.3.0' is not supported`

**Comment by jlblcc** [comment]
It's failing due to the schema version set in the mdJSON.

**Comment by stansmith907** [comment]
Ah! So I am testing mdJson file's mdJson.schema.version against the mdJson reader VERSION.  I must be slipping, can't remember what I coded a year and a half ago.  

The tests only check single sections at a time.  I'll need to work this into the testing sequence.  Have it by this weekend.  In the meantime, you can always set the mdJson schema version back to 2.2 in your files.

**Comment by jlblcc** [comment]
I can't remember what I coded two weeks ago! :roll_eyes: 

Yep, I just set the version back for now.

**Comment by stansmith907** [comment]
Patched.  I'll issue a PR for mdTranslator version 2.5.0.
