### ISSUE TITLE
sbJSON identifier objects are not unique

### ISSUE THREAD

**Issue by jlblcc** [adiwg/mdTranslator#162]
sbJSON identifier objects should be [uniq](https://ruby-doc.org/core-2.4.0/Array.html#method-i-uniq-21). 

Identifiers are repeated if the citation.identifier and metadataIdentifier are the same - probably can just uniq! the array.

**Comment by stansmith907** [comment]
What constitutes duplication? ID only? ID plus name space? All fields? 
BTW I have had trouble with uniq!, It doesn't always clear duplicates. I switched to reassigning using uniq.

**Comment by stansmith907** [comment]
Only ID and namespace are written to sbJson so other fields are not relevant.  Drop one record only is both the ID and namespace match.
