### ISSUE TITLE
Include citation.onlineResource and metadataOnlineResource in webLinks

### ISSUE THREAD

**Issue by jlblcc** [adiwg/mdTranslator#165]
The following onlineResources are not currently being translated to sbJSON:

`metadata/resourceInfo/citation/onlineResource` for a web page about the resource itself
`metadata/metadataInfo/metadataOnlineResource` for a web page with further descriptions

It would be good if these were both translated (when available) to webLinks in sbJSON, so they are prominently visible and clickable  in ScienceBase.

See adiwg/mdEditor#136

**Comment by zephyrr** [comment]
Yay, we really want this.  We have links in one or both fields for most of our projects, and would love to have them available as clickable "WebLinks" in ScienceBase.

**Comment by stansmith907** [comment]
Done.
