### ISSUE TITLE
De-Normalize contacts in internal data store

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdTranslator#17]
Writing the HTML writer I have run into a problem of sorts that got me thinking about the structure of the internal data store.  We normalized contacts in mdJson and that works well.  I kept that normalization in the internal data store and now find it inconvenient when writing liquid templates since liquid does not allow any code imbedded within a template.  I can likely find a way to work through this but raised a bigger question.  

If we normalize contacts in the internal data store then every reader will either need to have a normalized contact section or figure out how to collect the scattered contacts and build the normalized contact block in the data store.  Is this a restriction we want to place on all future readers?  If not work needs to be done to the mdTranslator.

De-normalizing the contacts in the internal data store will not be too much work.  It should also be relatively easy to change in the two ISO writers.  The bulk of the work will be in the mdJson reader which will need to distribute the contacts to each responsibleParty.  Also most all the unit test cases will need to be rewritten - the examples should be fine - since this is the content we wrote test cases for first.  

Thoughts?

**Comment by jlblcc** [comment]
My first reaction is to vote :+1: for keeping the contacts store as is. If I was writing a reader and thought it was going to be too inefficient/difficult to collect contacts in a normalized block, I could easily push each contact into the contacts array using a unique id for every instance of a contact. That would result in some bloat in the contacts array, but it would fit the current model for the internal store. It also would allow me to add the contacts on a case-by-case basis without scanning the entire input.

**Comment by stansmith907** [comment]
Bloated but efficient. I'll see if there is a way to pass more than one hash to a liquid template and scan through it once it's there.

**Comment by stansmith907** [comment]
Switching HTML writer from liquid to builder.  With builder I have full access to Ruby logic and de-normalization is not necessary.
