### ISSUE TITLE
Should FGDC writer requirements be relaxed?

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdTranslator#170]
I don't think we should relax the FGDC standard, or any standard's requirements.  That changes the standard and creates an ADIwg profile similar to NAP (North American Profile).  We maybe should find a way to pass the result out of the writer even when the writer fails.  

The ISO and FGDC writers do not stop processing when a requirement is not met, they just set `writerPass=false` and place a message in `writerMessages` then continue to process.  How this is handled is up to the rails-app and mdTools (I think).  

Perhaps we should add another flag to declare when strict adherence to a standard is required.  If 'lax', allow the write output to be presented, if 'strict' hold it back.  In both cases the `writerPass=false` attribute should be set and messages attached when required elements are missing.  In this scenario ISO and FGDC writers will behave as they do now - ISO includes the tags or missing elements by setting `nilReason='missing'` and FGDC just skips tags.  Note: Currently the ISO writers do not set `writerPass=false` when requirements are missing or accumulate messages.  

Changes would need to be made to mdTools and the demo to show the messages and still present the output.  The ISO writers would also need to be modified to accumulate messages.

**Comment by dwalt** [comment]
I agree with this requirement to enable standards adherence and allow for
pass through with an "adherence report" relative to a user's wishes.

**Comment by jlblcc** [comment]
I would suggest not trying to combing the metadata output and error reporting. I think it is fine if you get either one or the other. If "relax writer validation" = false or null(default), you get errors. If true, you get metadata with no validation. By default, the user's going to get an error report.

**Comment by stansmith907** [comment]
To clarify, the only thing returned by the translator, regardless of error status, is the `responseObj`.  The `responseObject` has both errors and the writer output embedded.  So it's just a matter of what we chose to show the user.  Either way I think users would (should) like to know what's missing even if they decide not to fix it.  It's a good safety check/review.  

I think the technical issue lies in the HTML response only being able to return a single object.  So it's either the whole `responseObj` or the `writerOutput`.  If the `responseObj` is returned then it's a matter of what catches it since it would take a program to separate the `writerOutput` from the `responseObject` (or a savvy user with a few tools).  

What you seem to suggest is to repress the writer validation errors and return only the `writerOutput`.  So if the user wants to know if her record is good, she will need to run it through the mdTranslator twice - once with validation and then again without.

**Comment by jlblcc** [comment]
> What you seem to suggest is to repress the writer validation errors and return only the writerOutput. So if the user wants to know if her record is good, she will need to run it through the mdTranslator twice - once with validation and then again without.

Yup. Most of the time that would happen anyway as the errors are fixed.

When using the CLI, the responseObject is just the metadata unless the -o flag is set (this is also true when using the API defaults).

**Comment by stansmith907** [comment]
The CLI -o option (`returnObject`) is only invoked when `writerPass=true`.  When writer validation fails you always get the full 'responseObject` returned.  

What your solution suggests is that when `writerValidation='lax'` we simply set `writerPass=true` regardless of any errors.  Thus there would be no way for user to know what writer specific errors to fix.  Only mdJson errors would be detected during read operations.

**Comment by jlblcc** [comment]
Yes, that is what I suggest we do. Otherwise, I have to process the object to get the "invalid" metadata. Having the ability to turn the writerValidation off, means I get the metadata directly. That's a lot simpler and would only happen if the user knowingly requests this option. The default state will return the errors.

I would suggest making the flag opt-in, e.g. writerValidationOff=true.

**Comment by jlblcc** [comment]
> I would suggest making the flag opt-in, e.g. writerValidationOff=true.

That could also be handled in the UI.
