### ISSUE TITLE
ISO Topic Category keywords not translated

### ISSUE THREAD

**Issue by jlblcc** [adiwg/mdTranslator#171]
It appears that ISO topic category keywords are being dropped when translating from FGDC. An example FGDC record is attached(file extension changed to .txt).

[Biological Planning Units & Aquatic Extensions for the Gulf Coast.shp edit.txt](https://github.com/adiwg/mdTranslator/files/1601763/Biological.Planning.Units.Aquatic.Extensions.for.the.Gulf.Coast.shp.edit.txt)

**Comment by dwalt** [comment]
The structure appears correct as does the keyword. Is the thesaurus name
consistent with the expected name by mdJSON? MP will optionally validate
ISO topic keywords and the spelling in this file reflects what MP expects.

**Comment by jlblcc** [comment]
FYI @betirpak

**Comment by stansmith907** [comment]
Checking the following:
- [x] mdJson reader
 * removed `resourceInfo.topicCategories[ ]` from internal object
 * continue to process mdJson 'topicCategory[ ]` as it is currently only deprecated, not removed
 * moved mdJson `topicCategory[ ]` items into `keywordType='isoTopicCategory'`
 * previously `keywordType='isoTopicCategory` were duplicated into `resourceInfo.topicCategories[ ]` for processing ISO output
- [ ] sbJson reader
- [ ] fgdc reader
- [ ] mdJson writer
- [ ] iso writer
- [ ] fgdc writer
- [ ] sbJson writer
- [ ] html writer
