### ISSUE TITLE
FGDC writer for voucher requires repository

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdTranslator#174]
In mdJson the voucher repository is a `responsibility` object (responsible party).  Responsibility requires a `role` and at least one `party` which is a `contactId`.  Since `party` is an array and FGDC can output only one contact the first contact is taken, others are ignored.  The FGDC reader automatically sets the repository role to 'curator'.  The mdJson reader sets it to whatever was specified in the mdJson record.  

The problem is that the FGDC writer is searching the responsibility object for a specific role type of 'custodian', which it may not be, in which case the repository output is skipped and an error message generated.  

Two problems here:
1. We need to decide what the role type of the specimen guardian should be.  'curator', 'custodian', '?'
2. There is actually no need to check the role type when processing the repository responsibility object since repository is not an array and only one role type is allowed per responsibility object.  Also, because the repository responsibility object is already placed in proper context any role should be acceptable.

**Comment by dwalt** [comment]
Just to clarify, voucher is an array in FGDC. However, as Stan pointed out,
only one citation is provided for per voucher reference. Often the citation
is an organization that is owner/custodian of the collection repository.
The person is usually offered as a contact point, if there is one. If you
want to use one role for both, then "custodian" may be best.

**Comment by stansmith907** [comment]
To clarify just a bit more, in mdJson and ISO voucher repository is a 'responsibility` (new term for responsible party); in FGDC it is a 'contact'.  Citation is not part of voucher.  And contact can be either person or organization, no problem there.

'Custodian' is good for me.
