### ISSUE TITLE
Support for non-FGDC spatial reference?

### ISSUE THREAD

**Issue by jlblcc** [adiwg/mdTranslator#175]
How would I have to enter this SRS in mdJSON so that it's supported by the FGDC writer?

http://spatialreference.org/ref/epsg/nad83-alaska-albers/

Obviously, it has an EPSG code, but that's not going to fly for FGDC output, right?

**Comment by dwalt** [comment]
Correct, there is no support for EPSG in FGDC. You would need to provide
relevant parameters that describe datum, projection, and coordinate system.

**Comment by stansmith907** [comment]
Like this to support both FGDC and ISO...

````json
{
   "spatialReferenceSystem": [
      {
         "referenceSystemParameterSet": {
            "projection": {
               "projectionIdentifier": {
                  "identifier": "3338",
                  "namespace": "EPSG",
               },
               "projection": "parameters",
               "projectionName": "NAD83 Alaska Albers",
               "standardParallel1": 9.0,
               "standardParallel2": 99.0,
               "longitudeOfCentralMeridian": -9.0,
               "latitudeOfProjectionOrigin": 9.0,
               "falseEasting": 99999.0,
               "falseNorthing": 999999.0,
               "otherProjectionDescription": "other projection description"
            }
         }
      }
   ]
}
````
Include the `projectionIdentifier`, `projection`, and `projectionName` plus any required parameters as Dennis mentioned.  The ones above are obviously not appropriate. 

Also, `otherProjectionDescription` might be an easy possibility in the future.  The element is defined in FGDC documentation, but not completely - the tag name is missing.  I did include the element in mdJson, read it in from mdJson, but don't handle it in FGDC until I have done more research.

**Comment by stansmith907** [comment]
One touchy point ...
If EPSG:3338 is an SRS (Spatial Reference System) and not just a projection (which the link seemed to indicate) it would go in `referenceSystemIdentifier` not `projectionIdentifier` as shown above.  I am assuming that an SRS defines both the projection and the spheroid.  

But then your name does contain NAD83 even though the link states 'projection', so .....

````json
{
   "spatialReferenceSystem": [
      {
         "referenceSystemIdentifier": {
            "identifier": "3338",
            "namespace": "EPSG"
         },
         "referenceSystemWKT": "reference system WKT",
         "referenceSystemParameterSet": {}
      }
   ]
}
````

**Comment by dwalt** [comment]
The parameter values for Alaska Albers 83 are not correct from what I
found, unless you were only demonstrating concept. I created a reference
using Metavist, listed below. I used the domain value for Albers, rather
than add my own text for AK Albers 1983. One thing I noticed is that
Metavist insisted I provide some coordinate system information, namely
encoding method, then relative to "coordinate pair" selection  - abcissa
and ordinate resolution, finally, distance units.

 <spref>
    <horizsys>
      <planar>
        <mapproj>
          <mapprojn>Albers Conical Equal Area</mapprojn>
          <albers>
            <stdparll>55</stdparll>
            <stdparll>65</stdparll>
            <longcm>-154</longcm>
            <latprjo>50</latprjo>
            <feast>0</feast>
            <fnorth>0</fnorth>
          </albers>
        </mapproj>
        <planci>
          <plance>coordinate pair</plance>
          <coordrep>
            <absres>1.00</absres>
            <ordres>1.00</ordres>
          </coordrep>
          <plandu>meters</plandu>
        </planci>
      </planar>
      <geodetic>
        <horizdn>North American Datum of 1983</horizdn>
        <ellips>Geodetic Reference System 80</ellips>
        <semiaxis>6378137</semiaxis>
        <denflat>298.25722210088</denflat>
      </geodetic>
    </horizsys>
  </spref>

**Comment by stansmith907** [comment]
Right, the parameters were just examples, I didn't attempt to make them correct.  But your above comment will save Josh the trouble of looking them up 🥇 .  Also true, I should have included the 'planar coordinate information' section as this is another FGDC requirement.  I'll edit the above mdJson to show how this would be specified.

**Comment by jlblcc** [comment]
Yeah, this is what I was expecting. I'm wondering how to make this easier in the editor. For SRSs supported in the codelists, it's relatively straight-forward, but it's rather complicated for the layman to have to define all those params. I'm thinking adding support to auto-fill the params based on EPSG, possibly using https://github.com/Esri/projection-engine-db-doc to lookup the params.

**Comment by stansmith907** [comment]
I think FGDC users would love it.
