### ISSUE TITLE
Dictionary domainItem reference

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdTranslator#180]
In FGDC each domain item has a value, definition, and *definition source*.  When I constructed the FGDC reader I did not import the definition source figuring that a single reference (citation) for the whole domain should be sufficient.  Now that I'm writing it back out, I wonder.

The FGDC standard requires a 'definition source' be specified for each enumerated domain item.  If we are strict to the standard we need something to fill the slot.  Looking at the example provided by Dennis I see all definition sources are the same - "author defined".  

To meet the FGDC standard I could take the `domainReference` and repeat its title in each domain item definition source tag.  This would require FGDC users to create a domain reference that cited the actual author - not just say "author defined"; but this limits each enumerated domain item to having the same definition  source. 

Also, there is no domain level reference in FGDC to harvest by an FGDC reader should someone be making a round trip.  Not a problem if coming from the mdEditor.

Choices:
 - [ ] add a domain item reference (citation) so each domain item definition can be separately cited.
 - [ ] use the domain reference (citation) title for each domain item when writing FGDC
 - [ ] the hybrid - add a domain item reference, make it optional, use the domain reference when the domain item reference is not provided. 
 - [x] and hybrid 2 - add a domain item reference, make it optional, write in "author defined" when the domain item reference is not provided. 
 - [ ] other ??

**Comment by dwalt** [comment]
If you were generating from an mdEditor sourced input, this would work.
However this would be burdensome for an existing FGDC record to require a
user to revisit every domain to tag an author. To be honest, this element
is not used very often beyond "author defined" to actually identify a
source citation. In these cases, this is usually for a national standard.
Some agencies, such as BLM, are much more advanced in utilizing standard
domains, so hard to say what people are doing with it. What about making a
default citation for "author defined"? Another thought is to grab the first
author name from the data citation  and use it.

**Comment by stansmith907** [comment]
Citation does not require a responsible party or a responsible party with role of 'author'.  So that would a  rule set specific to FGDC, which I would like to avoid.  I'm thinking I'll implement the hybrid above.  That will default the FGDC domain item definition source to the domain citation title.  If any domain item has some specific definition source other than the one listed in the domain, the user can enter a domain `itemReference` citation and its title will be used.  

This does require a schema change to domainItem.  That should make Josh happy!

**Comment by dwalt** [comment]
Josh will sing your praises...

So what is the domain citation title set to?

**Comment by stansmith907** [comment]
I think I'll change this up a bit more...

If a domainItem `reference` is defined its title will be used as the FGDC enumerated value definition source.  If the `reference` is not defined "author defined" with be written in.  The `domainReference` will not be used here.  I'll adjust the original message to reflect this post.

**Comment by stansmith907** [comment]
Good question for best practices.  "author defined" is not very specific either.  It implies there should be a responsible party of author somewhere in the metadata record.  

Having a citation as the `reference` allows for specific detail, although the detail would not make it into the FGDC record.  The citation itle could be ITIS or GCMD or USGS ASC Biology and include a responsible party of 'Dennis' with role of 'metadata author'.  ISO 19110 does allow for this reference at the enumerated item level.

**Comment by dwalt** [comment]
Agreed, not best practice. Generally considered a nitpicky, redundant
detail in common usage. If a specific published domain was used, this is
specified in the attribute definition source. Technically, definition and
domain source are two separate things, but in common usage there are
rarely, if ever, different sources.

**Comment by jlblcc** [comment]
So we're talking about adding an optional itemReference(citation) to the domainItem object? Not a big deal in the schema. Kinda a pain in the editor, since citation is huge.  Since there's only four properties, I think I can deal with it so folks don't have to navigate to s sub-route unless thy want to enter more than the title. 

Ironically, I'm working on the domainItem template now- so now would be a good time if you want to do so.

**Comment by stansmith907** [comment]
To Josh - yep.  I would like to name it `ItemReference` but we called the other elements `name`, `value`, and `definition`; so I called it 'reference`.  `itemReference` looked out of place.  But whatever you decide is good with me.

**Comment by stansmith907** [comment]
To Dennis - since all this is moving in and out of mdJson, domains are normalized and separate from attributes.  In both FGDC and ISO the are integrated.  So we do have a separate `entityReference`, `attributeReference`, `domainReference`, and now `itemReference`.  Let's here it for citations!
