### ISSUE TITLE
Divide user messages into warning and error

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdTranslator#183]
Divide user messages into warning and error categories.  Add a header to each message of WARNING: or ERROR:.  Errors will set the response object stage pass flag to 'false'; warnings will leave the flag status unchanged.

Rules for determining warnings and errors:
* reader structure issues are errors - 
   * the reader is unable to parse the input
   * no reader was specified
   * no input file found
* reader validation issues are errors -
   * currently only mdJson is validated.  Messages indicate the schema has been violated
* reader execution issues depend on the reader -
   * fgdc - input is tested against the FGDC standard.  Most messages are warnings to allow translation to mdJson and cleanup in the mdEditor.  Violations to the FGDC standard were not checked in the `fgdc` reader, these will need to be added to all reader modules. 
   * mdJson - most of these are errors as they would prevent clean translation to other standards. 
 Many of these tests were already preformed and flagged by schema validator so are likely duplicates  These could possibly be removed.
   * sbJson - no validation is done by the translator.
* writer execution issues are mostly warnings - these indicate the generated output does not fully meet the standard's requirements.  We seem to be adopting a liberal policy in regards to strict adherence to a standard output.  For some data types aspects of a standard may be inappropriate and in cases of legacy data some metadata may be lost.  Warning messages alert the user when the following action action has been taken #178. 
   * ISO 19115-2, 19110 tags of missing required elements are attributed with `nilReason` so the records still pass XSD validation.  
   * FGDC missing elements are represented with empty tags regardless of `showAllTags` status.  
   * sbJson has no requirements, so no messages.
   * HTML is a report of what is held in the internal object, so no messages.

Progress:
 - [x] fgdc reader - added warning messages for all missing required elements; modified 111 files
 - [x] mdJson reader - revised messages; set error status for missing required elements; set warning status for deprecated and empty elements; modified 214 files.
 - [ ] fgdc writer
 - [ ] iso 19110 writer
 - [ ] iso 19115-2 writer
 - [ ] mdJson writer

**Comment by jlblcc** [comment]
It might be useful to implement messages as static constants in a "message" class or mixin. Messages could be re-used across modules, and it would be easier to edit error messages with them all in one place. It would also make it easier to implement internationalization, if we ever get a request for that.

**Comment by stansmith907** [comment]
I can start implementation in the writer messages since I am currently working this section and have already partially implemented the idea, but I will wait to revisit the reader messages just recently published.

**Comment by jlblcc** [comment]
Cool, Yeah, we can worry about the reader messages in a future refactor. Should we create an issue to track that?
