### ISSUE TITLE
Error Translating to sbJSON 2.4.5 Not Supported

### ISSUE THREAD

**Issue by jbadash** [adiwg/mdTranslator#188]
I've downloaded a JSON file from ScienceBase, run it through the mdTranslator, and output an mdJSON file. I successfully loaded the file into mdEditor and repaired any noted errors. Upon attempting to publish to ScienceBase I get the following 400 error:
 "Error transforming to sbJson. mdJson schema version '2.4.5' is not supported. mdJson versions '2.0.0' to '2.3.2' are supported"

Is this an mdTranslator issue or an mdEditor issue? Can I output a file from mdTranslator with an older schema?

I've attached both files as a Zip

Thanks,
Joe
[Pennsylvania_Watersheds_sbJSON_and_mdJSON.zip](https://github.com/adiwg/mdTranslator/files/1834289/Pennsylvania_Watersheds_sbJSON_and_mdJSON.zip)

**Comment by jlblcc** [comment]
This is a result of ScienceBase using an older version of the mdTranslator in their application stack. I believe they are in the process of updating to the latest version. @jllong-usgs do you have any info on the timeframe for this?

**Comment by jbadash** [comment]
Thanks Josh. I'll await jllong's reply.


jbadash@fergusonlynch.com

Phone: (505)353-0935

**Comment by jwaspin** [comment]
This can't possibly still be an issue, we're on mdJson schema version 2.8.2 and I have seen this issue when mdEditor and mdTranslator have a version mismatch with mdJson-schemas which at the moment should be fixed.
