### ISSUE TITLE
Make sure topicCategories are compatible with ISO version

### ISSUE THREAD

**Issue by jlblcc** [adiwg/mdTranslator#196]
The [topicCategory codelist](https://www.adiwg.org/mdTools/#codes-page?c=iso_topicCategory) is based on 19115-1, so all the options are not valid when writing 19115-2 (extraTerrestrial, disaster). Since topicCategories is not extendable, this causes a validation failure in 19115-2 records. I suggest we strip the 19115-1 additions when generating 19115-2.

**Comment by stansmith907** [comment]
Fixed in 2.13.1
