### ISSUE TITLE
Errors Translating FGDC to HTML

### ISSUE THREAD

**Issue by dwalt** [adiwg/mdTranslator#201]
In testing a translation from FGDC to HTML, noticed some errors with translating citations. In this example, the larger work citation from FGDC resulted in two identical larger work citations in Associated Resources. I believe the first one was correctly translated from the FGDC larger work citation. The second one came from a redundant larger work citation from the FGDC record within the cross reference section, discussed below.

In the FGDC file there are two cross reference citations, the second one has a larger work citation. This scenario is rarely used, but is valid in FGDC. The translator appears to have translated the larger work citation as a larger work citation in Associated Resources, which mirrors the first entry. Then it created the second cross reference citation as a cross reference associated resource. In the title it appended the cross reference title to the end of that citation's larger work citation title.

The first cross reference citation in the FGDC file was not translated.

Attached source file with a txt file type sufffix.
[GulkanaGlacier_RawGPR.txt](https://github.com/adiwg/mdTranslator/files/2307581/GulkanaGlacier_RawGPR.txt)

**Comment by stansmith907** [comment]
Checking the input file GulkanaGlacier_RawGPR.xml I found two largerWorkCitation tags: one in metadata > idinfo > citation > citeinfo; and another in metadata > idinfo > crossref[2] > citeInfo as you stated.  They appear to be identical in the XML.  This resulted in 2 associated resources which are identical.  All FGDC larger work citations are mapped to associated resources.  I don't see any difference between the two instances when I translated to HTML using mdTranslator version 2.13.2.  

What am I missing?

![largerworkcitation](https://user-images.githubusercontent.com/4998910/45125333-7f6e4800-b11a-11e8-818b-82e7c75ab26a.png)

**Comment by stansmith907** [comment]
Thanks.  The problem was mdTranslator was processing cross references as a scalar object when in fact it is an array.  The way XPATH works, it then places all occurrences in the same object.  Fixed now.  Except that, in mdJSON I have no way to preserve the relationship for a larger work citation that has it's own cross reference.  Both just become independent associated resources.  

![crossref2](https://user-images.githubusercontent.com/4998910/45176562-d9bfe500-b1bc-11e8-853f-b432d33813c1.png)

Let me know if this works for you.  If so I'll close the issue.

**Comment by dwalt** [comment]
Correct, crossref is an array in FGDC. This looks right now. In order to
preserve the larger work citation relationship, associated resource would
need to be recursive, something I'm not sure ISO supports. While FGDC
allows this referencing, I personally don't think it is a good practice as
it goes beyond direct relevance to the resource described. We can call it
good for now, acknowledge it as an FGDC mapping issue and see it any actual
requirement for it pops up.

**Comment by stansmith907** [comment]
Thanks, I'll close the issue and publish the update.
