### ISSUE TITLE
Intermittent output of liabilityStatement

### ISSUE THREAD

**Issue by hmaier-fws** [adiwg/mdTranslator#220]
The distribution liability statement `metadata{ } > resourceDistribution[ ] > distribution{ } > liabilityStatement` is output for some records but not others. The liabilityStatement is present in the JSON, is displayed in the editor and the mdJSON passes validation.

**Comment by dwalt** [comment]
-2 and HTML writers. liabilityStatement written twice in successful translations, possible issue with mdEditor.

**Comment by hmaier-fws** [comment]
This seems to be the same issue as #236

**Comment by jwaspin** [comment]
PR created https://github.com/adiwg/mdEditor/pull/557

**Comment by jwaspin** [comment]
@dwalt @hmaier-fws I'm pretty sure we can close this issue, it was resolved in mdEditor

**Comment by jwaspin** [comment]
As discussed, we think this issue can be closed. If it ends up not being resolved we probably want a new ticket anyway.
