### ISSUE TITLE
Support 19115-1 Amd 1-2018

### ISSUE THREAD

**Issue by dwalt** [adiwg/mdTranslator#222]
Support for 19115-1:2014/AMD 1:2018. 

Related Issues: 
mdJSON Schemas: https://github.com/adiwg/mdJson-schemas/issues/242

- [x] contact>identifier
- [ ] spatialRepresentation>scope
- [ ] coverageDescription>rangeDimension>sampleDimension>
rangeElementDescription

**Comment by dwalt** [comment]
Verified sbJSON supports identifiers:

sbJSON: contacts[]>orcId
	i.	Logic: where contactType = “individual” and “orcId” element exists
	ii.	contacts block
		1.	identifier: orcId
		2.	namespace: “ORCID”
		3.	version: (not supported)
		4.	description: “Open Researcher and Contributor Id”
		5.	authority{}: (not supported)
sbJSON: contacts[]>organization
	i.	Logic: where contactType = “organization” and “organization” block element exists = true
	ii.	contacts block
		1.	identifier: directoryId
		2.	namespace: displayText
		3.	version: (not supported)
		4.	description: displayText
		5.	authority{}: (not supported)

**Comment by hmaier-fws** [comment]
@jwaspin can you confirm that `spatialRepresentation` with the `scope` addition has been to:
  - translator reader
  - translator internal object

**Comment by jwaspin** [comment]
@hmaier-fws Yes, I can confirm. @chris-macdermaid and I went through and verified the scope was there for the readers, writers, and internal obj.

For the [internal object, spatial representation](https://github.com/adiwg/mdTranslator/blob/develop/lib/adiwg/mdtranslator/internal/internal_metadata_obj.rb) is defined starting at line 1184 and all 4 representation types have the scope array.
Readers: [mdJson](https://github.com/adiwg/mdTranslator/blob/develop/lib/adiwg/mdtranslator/readers/mdJson/modules/module_spatialRepresentation.rb)
Writers: [mdJson](https://github.com/adiwg/mdTranslator/blob/develop/lib/adiwg/mdtranslator/writers/mdJson/sections/mdJson_spatialRepresentation.rb), [html](https://github.com/adiwg/mdTranslator/blob/develop/lib/adiwg/mdtranslator/writers/html/sections/html_spatialRepresentation.rb), [iso19115-3](https://github.com/adiwg/mdTranslator/blob/develop/lib/adiwg/mdtranslator/writers/iso19115_3/classes/class_spatialRepresentation.rb) all contain the scope for each representation type
