### ISSUE TITLE
Add HTML writer

### ISSUE THREAD

**Issue by jlblcc** [adiwg/mdTranslator#23]
The SRS section says *Well-Know-Test*. Should be *Well-Known-Text*. :laughing:

**Comment by jlblcc** [comment]
I vote to drop the left border on the \<blockquote\>'s. I think it's distracting. :+1: or :-1:  ?

**Comment by jlblcc** [comment]
We should have an option for folks to pass a reference to their own stylesheet.

**Comment by stansmith907** [comment]
- [x] Fixed the Test/Text typo 
- [ ] Like the option for user stylesheet, will add that.  
- [ ] And as you know I like the guide lines on the left border

**Comment by jlblcc** [comment]
User stylesheets aren't supported yet, right? Should we create a separate issue for that?
