### ISSUE TITLE
CSDGM Writer Entity Tag Errors

### ISSUE THREAD

**Issue by dwalt** [adiwg/mdTranslator#231]
Entity type tag should be "enttyp" instead of the current "enttype". Error causes entity section not readable in CSDGM editors and or errors as well as failing validation in the Metadata Parser validator.

**Comment by dwalt** [comment]
mdJSON-CSDGM translated successfully in test

**Comment by jwaspin** [comment]
#132 is related

**Comment by jwaspin** [comment]
Closed by #237
