### ISSUE TITLE
CSDGM Writer - Orphaned End Tags

### ISSUE THREAD

**Issue by dwalt** [adiwg/mdTranslator#232]
End tags in the Distribution section are showing up absent beginning tags or content. This includes Technical Prerequisites (techpreq) and Resource Description (resdesc).

**Comment by timothypage** [comment]
@dwalt it looks like `techpreq` and `resdesc` are configured to always output an empty tag (`<techpreq />`)if they're empty, if thats what you mean?
- https://github.com/adiwg/mdTranslator/blob/master/lib/adiwg/mdtranslator/writers/fgdc/classes/class_distribution.rb#L143-L145
- https://github.com/adiwg/mdTranslator/blob/master/lib/adiwg/mdtranslator/writers/fgdc/classes/class_distribution.rb#L71-L73

I can either remove those lines or put it behind the "writerShowTags" configuration, [like this](https://github.com/adiwg/mdTranslator/blob/master/lib/adiwg/mdtranslator/writers/fgdc/classes/class_distribution.rb#L97-L99)

**Comment by dwalt** [comment]
It should not write empty tags, unless the "show empty tags" switch is set.
________________________________
From: Tim Zwolak ***@***.***>
Sent: Tuesday, October 18, 2022 1:12 PM
To: adiwg/mdTranslator ***@***.***>
Cc: Walworth, Dennis H ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [adiwg/mdTranslator] CSDGM Writer - Orphaned End Tags (Issue #232)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@dwalt<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdwalt&data=05%7C01%7Cdwalworth%40usgs.gov%7Ccda50325c0804d487e7308dab14d874b%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638017243785862236%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=eyJOOZbVTL1AdYfbH5cwYO2bVhNxk9afuLJcV3bxsdM%3D&reserved=0> it looks like techpreq and resdesc are configured to always output an empty tag (<techpreq />)if they're empty, if thats what you mean?

  *   https://github.com/adiwg/mdTranslator/blob/master/lib/adiwg/mdtranslator/writers/fgdc/classes/class_distribution.rb#L143-L145<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fadiwg%2FmdTranslator%2Fblob%2Fmaster%2Flib%2Fadiwg%2Fmdtranslator%2Fwriters%2Ffgdc%2Fclasses%2Fclass_distribution.rb%23L143-L145&data=05%7C01%7Cdwalworth%40usgs.gov%7Ccda50325c0804d487e7308dab14d874b%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638017243785862236%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=mDqBR%2FfdwdEv9%2FdLgQiZq0IJGBChiUe9W7mzS2eb%2BHw%3D&reserved=0>
  *   https://github.com/adiwg/mdTranslator/blob/master/lib/adiwg/mdtranslator/writers/fgdc/classes/class_distribution.rb#L71-L73<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fadiwg%2FmdTranslator%2Fblob%2Fmaster%2Flib%2Fadiwg%2Fmdtranslator%2Fwriters%2Ffgdc%2Fclasses%2Fclass_distribution.rb%23L71-L73&data=05%7C01%7Cdwalworth%40usgs.gov%7Ccda50325c0804d487e7308dab14d874b%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638017243785862236%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=0zhiLpuHJ%2Fcg5eyZqO4dZqOJE5CfILZeEbBKx8VERzA%3D&reserved=0>

I can either remove those lines or put it behind the "writerShowTags" configuration, like this<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fadiwg%2FmdTranslator%2Fblob%2Fmaster%2Flib%2Fadiwg%2Fmdtranslator%2Fwriters%2Ffgdc%2Fclasses%2Fclass_distribution.rb%23L97-L99&data=05%7C01%7Cdwalworth%40usgs.gov%7Ccda50325c0804d487e7308dab14d874b%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638017243785862236%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=lSvDhk4b2Z%2BeWqdawLknj%2Fwwsy5M6PZPSxKCZ60ZShQ%3D&reserved=0>

**Comment by dwalt** [comment]
mdJSON-CSDGM translated successfully in test

**Comment by hmaier-fws** [comment]
closed by #250
