### ISSUE TITLE
CSDGM Reader - Altitude Units Missing

### ISSUE THREAD

**Issue by dwalt** [adiwg/mdTranslator#235]
Altitude Units (altunits) from CSDGM input is not translating to mdJSON: [schema{ } > metadata{ } > resourceInfo{ } > extent[ ] > object{ } > geographicExtent[ ] > object{ } > boundingBox{ } > unitsOfAltitude](https://mdtools.adiwg.org/#permalink-popup)

**Comment by timothypage** [comment]
@dwalt I'm able to get unitsOfAltitude to import with the following CSDGM

both "minimumAltitude" and "maximumAltitude" are required to be present on writing mdJson to CSDGM, but it doesn't look like the reverse is true, it will just throw a warning

[boundingBox-alititude.xml.zip](https://github.com/adiwg/mdTranslator/files/9832520/boundingBox-alititude.xml.zip)

**Comment by timothypage** [comment]
I didn't see any altitude stuff in mdEditor, so crafted the above xml by hand

**Comment by dwalt** [comment]
mdEditor does not support Bounding Box Altitudes, but mdJSON does: schema{ } > metadata{ } > resourceInfo{ } > extent[ ] > object{ } > geographicExtent[ ] > object{ } > boundingBox{ } > unitsOfAltitude<https://mdtools.adiwg.org/#permalink-popup>

In this example, a CSDGM file was imported to mdJSON. In the enclosed screen shots, you can see the altitude unit tags are missing entirely, though both min and max altitude was provided.

________________________________
From: Tim Zwolak ***@***.***>
Sent: Thursday, October 20, 2022 9:34 AM
To: adiwg/mdTranslator ***@***.***>
Cc: Walworth, Dennis H ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [adiwg/mdTranslator] CSDGM Reader - Altitude Units Missing (Issue #235)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



I didn't see any altitude stuff in mdEditor, so crafted the above xml by hand

**Comment by dwalt** [comment]
@timothypage  mdEditor does not support Bounding Box Altitude, but mdJSON does: [schema{ } > metadata{ } > resourceInfo{ } > extent[ ] > object{ } > geographicExtent[ ] > object{ } > boundingBox{ } > unitsOfAltitude](https://mdtools.adiwg.org/#permalink-popup)

In this example, a CSDGM file containing Altitude was imported into mdJSON. The altitude unit tags do not appear in the mdJSON file, even though altitude min, max and units existed in the source file.

![boundBox_altUnits_CSDGM](https://user-images.githubusercontent.com/6201647/197037341-8138402b-2973-4d9e-ae94-32029852e5ed.GIF)

![boundBox_altUnits_mdJSON](https://user-images.githubusercontent.com/6201647/197037391-bdcaeded-c16f-4cd6-9d85-b60f8876b48a.GIF)

**Comment by timothypage** [comment]
@dwalt ahhhh, it's `altunit` in the fgdc reader, changing to `altunits`

**Comment by dwalt** [comment]
Still not working. Tag is now writing, but data still null.

"boundingBox": {
"westLongitude": -148.87,
"eastLongitude": -148.35,
"southLatitude": 63.95,
"northLatitude": 64.24,
"minimumAltitude": 20,
"maximumAltitude": 40,
"unitsOfAltitude": ""
},

**Comment by hmaier-fws** [comment]
closed by #250
