### ISSUE TITLE
sbJSON Citation Revision

### ISSUE THREAD

**Issue by dwalt** [adiwg/mdTranslator#240]
Currently, translation to sbJSON (and publish to Science Base function in mdEditor) constructs a citation from the author list, title, and URI. There are two problems with this:

1. Author roles and date roles are being included within parenthesis, which are not appropriate in true citations.
2. The citation format does not meet USGS FSP policies for data citations. 

The appropriate formatted citation exists in citation > otherCitationDetails { } for USGS records. Ex: Bender, A.M., Nolan, M., 2021, Fodar orthomosaic and digital elevation model of the Totatlanika River corridor (Alaska) acquired August 2021: U.S. Geological survey data release, https://doi.org/10.5066/P9K7CFRI

A few potential solutions:

1. Look for existence of otherCitationDetails content and use it first, use constructed citation if non-existent. Risk of otherCitationDetails containing information unrelated to citations.
2. Ask user for a preference, which could only be implemented in the Publish to Science Base interface.
3. Modify the citation construction to conform to USGS policies. Note, USGS citation policies are based on guidelines developed by ESIP.
4. Behind the scenes scripting in Science Base to overwrite the citation.

**Comment by jwaspin** [comment]
@dwalt Just to confirm, I am planning to do the following for this:

- [ ] Remove dates
- [ ] Filter parties to only authors

**Comment by dwalt** [comment]
@jwaspin No, there are two use cases:
1.  If the user provided Other Cit Details, then use that
2. If Other Cit Details is null, then provide a basic citation of: author(1), author(2)..., Citation Title
ex: Fred Flintstone, Barney Rubble, Geology of the Stone Age
