### ISSUE TITLE
Feature/Data Quality

### ISSUE THREAD

**Issue by dwalt** [adiwg/mdTranslator#243]
- [ ]  mdJSON Translation to html successful, but missing scope, label and citation
- [ ]  CSDGM Translation to mdJSON successful, but missing scope and label: suggest hard coded defaults of tabularDataset for scopeCode and "CSDGM Data Quality" for a default label

**Comment by jwaspin** [comment]
Was PR #241 sufficient to close this?

Related?
https://github.com/adiwg/mdJson-schemas/issues/262
https://github.com/adiwg/mdJson-schemas/issues/256
