### ISSUE TITLE
Tag/Release v2.18.2

### ISSUE THREAD

**Issue by jwaspin** [adiwg/mdTranslator#273]
According to GitHub this repo is still at version 2.17.1, but the latest published ruby gem is 2.18.2.

As of today, master is what was published as 2.18.2 so the most recent commit to master looks like the commit that should be tagged.

Since v2.18.2 has been published it probably makes sense to also designate this commit as a release.

**Comment by hmaier-fws** [comment]
Tagged master as v2.18.2 and published as latest release
