### ISSUE TITLE
Pre-formatted text in HTML writer

### ISSUE THREAD

**Issue by jlblcc** [adiwg/mdTranslator#37]
How about wrapping elements that typically have pre-formatted text blocks, i.e. paragraphs, in ```<pre>``` tags. Otherwise my new lines are ignored(along with any other white space) when rendered as HTML. Would be especially useful for *abstract*.

**Comment by jlblcc** [comment]
Another option would be to add classes to the sections and use the [```white-space```](https://developer.mozilla.org/en-US/docs/Web/CSS/white-space) property in the CSS. I'm mainly concerned about preserving line-breaks, so ```white-space: pre-line;``` would fit my requirements and be the least intrusive option.

**Comment by stansmith907** [comment]
That looks good.  Another CSS property I had not known of.  I'll work it
in.  Create an issue for version 1.3?

On Fri, Jul 10, 2015 at 8:42 AM, Josh Bradley <notifications@github.com>
wrote:

> Another option would be to add classes to the sections and use the
> white-space <https://developer.mozilla.org/en-US/docs/Web/CSS/white-space>
> property in the CSS. I'm mainly concerned about preserving line-breaks, so white-space:
> pre-line; would fit my requirements and be the least intrusive option.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/adiwg/mdTranslator/issues/37#issuecomment-120455404>.
>



-- 
Stan Smith
Alaska Science Center
Data Manager
907-786-7072 Office
907-223-8752 Mobile
stansmith@usgs.gov

**Comment by jlblcc** [comment]
I created a new branch and pull request, #38, with my solution. I only added the new .pre-line class to abstract section. Note that spaces and tabs will still collapse when using ```white-space: pre-line;```.

Also, note the change to the ruby code. I refactored to use !tag instead of !text to prevent the extra newline. See https://github.com/jimweirich/builder/issues/45. This will also need to be taken into consideration whenever .pre-line is applied.

**Comment by stansmith907** [comment]
The white-space: pre-line; works for me.

Not sure what the advantage of moving the section tag into a tag! method
buys.  It does create better formatted html than using text!, but there are
many places we still need to use the text! method.  Any time we need to do
processing inside a tag or have multiple items to write within a tag, I
think we will still need the text! method.  I think I prefer consistency
rather than cleaning up just some of the html.  That said, the html is
already inconsistent.

On Fri, Jul 10, 2015 at 12:05 PM, Josh Bradley <notifications@github.com>
wrote:

> I created a new branch and pull request, #38
> <https://github.com/adiwg/mdTranslator/pull/38>, with my solution. I only
> added the new .pre-line class to abstract section. Note that spaces and
> tabs will still collapse when using white-space: pre-line;.
>
> Also, note the change to the ruby code. I refactored to use !tag instead
> of !text to prevent the extra newline. See jimweirich/builder#45
> <https://github.com/jimweirich/builder/issues/45>. This will also need to
> be taken into consideration whenever .pre-line is applied.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/adiwg/mdTranslator/issues/37#issuecomment-120509167>.
>



-- 
Stan Smith
Alaska Science Center
Data Manager
907-786-7072 Office
907-223-8752 Mobile
stansmith@usgs.gov

**Comment by jlblcc** [comment]
The problem with using ```text!``` with ```.pre-line``` is the extra new-line that's added. Normally, this would be collapsed when rendered in the browser, but not when ```white-space: pre-line;``` is applied.

**Comment by jlblcc** [comment]
Fixed by adae8c8000af54c45ee061f1c63e9c126359d98f
