### ISSUE TITLE
Tests failing due to use of clone on class variable

### ISSUE THREAD

**Issue by jlblcc** [adiwg/mdTranslator#41]
Running ```rake TESTOPTS="--seed=26538"``` will cause a failure ([tc_reader_mdjson_metadataInfo.rb](https://github.com/adiwg/mdTranslator/blob/dev/test/readers/mdJson/v1/tc_reader_mdjson_metadataInfo.rb)) due to the order in which tests are being run, combined with the use of ```clone``` on a class variable(```@@hIn```). Clone produces a shallow copy. See [here for an explanation](http://thingsaaronmade.com/blog/ruby-shallow-copy-surprise.html).

Using ```Marshal::load(Marshal.dump(@@hIn))``` will fix the problem. A cleaner solution would be to rewrite the tests and remove dependency on the class variable(s).

**Comment by jlblcc** [comment]
See https://travis-ci.org/adiwg/mdTranslator/jobs/82585001 for another example(seed = 25850).

**Comment by stansmith907** [comment]
Replaced .clone with Marshal in all tests scripts.
