### ISSUE TITLE
sbJson 2.0 body

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdTranslator#55]
Mapping of sbJson body to mdTranslator internal data structure:
- [x] reader complete
- [x] writer complete

````json
{
    "body": "The main goal of this item is to show you how to create an item"
}
````
Definition: The ScienceBase Body is an open descriptive field for an item that may contain rich formatting (accessible by clicking the arrow button at the top right of the form field). The Body should provide users with a clear understanding of an item with as much formatting as necessary to give the user a clear reading experience.
 * Map to resource abstract: [schema][metadata][resourceInfo].abstract
[view mdTools](http://mdtools.adiwg.org/#viewer-page?v=2-1-2)

___
````json
{
  "summary": "The main goal of this item is to show ..."
}
````
Definition: A concatenated version of the body auto generated by ScienceBase.
 * Map to resource shortAbstract: [schema][metadata][resourceInfo].shortAbstract
[view mdTools](http://mdtools.adiwg.org/#viewer-page?v=2-1-2)
___
Mapping to mdTranslator
````ruby
   def newBase
      intObj = {
         metadata: {
            resourceInfo: {
               abstract: 'The main goal of this item is to show you how to create an item',
               shortAbstract: 'The main goal of this item is to show ...'
            }
         }
      }
   end
````
Translation to mdJson
````json
{
   "metadata": {
      "resourceInfo": {
         "abstract": "The main goal of this item is to show you how to create an item",
         "shortAbstract": "The main goal of this item is to show ..."
      }
   }
}
````

**Comment by jlblcc** [comment]
Need to make sure the text is escaped properly since it _may_ contain HTML markup.

**Comment by stansmith907** [comment]
summary field is auto populated and will overwrite the shortAbstract field.  

Lei Ann will check to see if this is true or not
