### ISSUE TITLE
sbJson 2.0 citation

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdTranslator#56]
Mapping of sbJson citation to mdTranslator internal data structure:
- [x] reader complete
- [x] writer complete

````json
{
   "citation": "Jay Diffendorfer, Roger Compton, Louisa Kramer, Zach Ancona, and Donna Norton, 2015-05, Onshore Industrial Wind Turbine Locations for the United States to March 2014: United States Geological Survey (USGS): Denver, CO, http://pubs.usgs.gov/ds/817/downloads/USGSWind_Turbine_03_2014.zip, http://dx.doi.org/10.3133/ds817, http://eerscmap.usgs.gov/windfarm/."
}
````
Definition: The citation that can be used to reference the item.
 * Map to resource citation otherCitationDetails: [schema][metadata][resourceInfo][citation][otherCitationDetails][n]
[view mdTools](http://mdtools.adiwg.org/#viewer-page?v=2-1-1-8)
___
Mapping to mdTranslator
````ruby
   def newBase
      intObj = {
         metadata: {
            resourceInfo: {
               citation: {
                  title: nil,
                  alternateTitles: [],
                  dates: [],
                  edition: nil,
                  responsibleParties: [],
                  presentationForms: [],
                  identifiers: [],
                  series: {},
                  otherDetails: [
                     'Jay Diffendorfer, Roger Compton, Louisa Kramer, Zach Ancona, and Donna Norton, 2015-05, Onshore Industrial Wind Turbine Locations for the United States to March 2014: United States Geological Survey (USGS): Denver, CO, http://pubs.usgs.gov/ds/817/downloads/USGSWind_Turbine_03_2014.zip, http://dx.doi.org/10.3133/ds817, http://eerscmap.usgs.gov/windfarm/.'
                  ],
                  onlineResources: [],
                  browseGraphics: []
               }
            }
         }
      }
   end
````
Translation to mdJson
````json
{
   "metadata": {
      "resourceInfo": {
         "citation": {
            "otherCitationDetails": [
               "Jay Diffendorfer, Roger Compton, Louisa Kramer, Zach Ancona, and Donna Norton, 2015-05, Onshore Industrial Wind Turbine Locations for the United States to March 2014: United States Geological Survey (USGS): Denver, CO, http://pubs.usgs.gov/ds/817/downloads/USGSWind_Turbine_03_2014.zip, http://dx.doi.org/10.3133/ds817, http://eerscmap.usgs.gov/windfarm/."
            ]
         }
      }
   }
}
````

**Comment by stansmith907** [comment]
sbJson *citation* was mapped to mdTranslator 'citation.otherDetails[]' since the sbJson *citation* is a formatted text citation and not possible to map back to citation elements.  This may create an issue when writing sbJson records from the translator; the first record in 'otherDetails' will likely not always be a/the formatted citation.

**Comment by jlblcc** [comment]
The writer should build the citation from the available properties. Not sure what to do with `otherCitationDetails'. I guess we can concatenate it at the end???

**Comment by stansmith907** [comment]
Maybe.  Not sure how many of the necessary citation details we may have; enough to build a text citation?  Are all the parts needed required in sbJson?  And should the assembled citation have preference over the provided *citation* for context for which it is used in ScienceBase.

**Comment by jlblcc** [comment]
Well, I guess at minimum we'll have a title and onlineResource(usually). Date(s) can be included if present, ditto contacts. This is an example of what is output in the current writer:

```Tom Heinrichs, Jess Grunblatt, Jessica Cherry, PhD, Amy Jacobs, Jennifer Delamere, Will Fisher, Cheryl Hasse, Joshua Bradley, Jennifer Lynn Jenkins, 2013-05-01(creation), Imiq - Hydroclimate Database and Data Portal, http://arcticlcc.org/projects/ALCC2013-08```

There's no way to reliably retrieve the information inserted into `otherDetails`. The citation in sbJSON could be anything.

**Comment by stansmith907** [comment]
On reading sbJson, the citation data will be placed in citation < otherDetails.
On writing sbJson the resourceInfo < citation will be parsed to create the core citation.  
Look at original writer for format of citation.  Will need to add names from citation < responsibleParty and pointOfContact.

**Comment by stansmith907** [comment]
We need a definition of citation format.  
Need to document what person, organization roles should be included along with their precedence.  
Need to document what date types should be included in citation.
