### ISSUE TITLE
sbJson 2.0 link

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdTranslator#58]
Mapping of sbJson link to mdTranslator internal data structure:
- [x] reader complete
- [x] writer complete

````json
"link":
{
    "rel":"self",
    "url":"<full url of item or search>",
    "nextlink":
    {
        "rel":"next",
        "url":"<url of next result>"
    },
    "prevlink":
    {
        "rel":"prev",
        "url":"<url of previous result>"
    },
    "relatedItems":
    {
        "rel":"related",
        "url":"<url of related items list>"
    }
}
````
Definition... 
 * rel:  "rel" tells you what you are looking at. For items this will always be "self".
Map to resource citation onlineResources description: 
[schema][metadata][resourceInfo][citation][onlineResources][n].olResDesc
[view mdTools](http://mdtools.adiwg.org/#viewer-page?v=2-1-1-9-0-3)
 * url: (none)
Map to resource citation onlineResources uri: 
[schema][metadata][resourceInfo][citation][onlineResources][n].olResUri
[view mdTools](http://mdtools.adiwg.org/#viewer-page?v=2-1-1-9-0-0)
 * nextLink: (not mapped)
 * prevLink: (not mapped)
 * set onlineResources function = 'navigation'
[schema][metadata][resourceInfo][citation][onlineResources][n].olResFunction
[view mdTools](http://mdtools.adiwg.org/#viewer-page?v=2-1-1-9-0-4)
___
Mapping to mdTranslator
````ruby
   def newBase
      intObj = {
         metadata: {
            resourceInfo: {
               citation: {
                  onlineResources: [
                     {
                        olResURI: '<full url of item or search>',
                        olResProtocol: nil,
                        olResName: nil,
                        olResDesc: 'self',
                        olResFunction: 'navigation'
                     }
                  ]
               }
            }
         }
      }
   end
````
Translation to mdJson
````json
{
   "metadata": {
      "resourceInfo": {
         "citation": {
            "onlineResource": [
               {
                  "uri": "<full url of item or search>",
                  "protocol": "",
                  "name": "",
                  "description": "self",
                  "function": "navigation"
               }
            ]
         }
      }
   }
}
````

**Comment by jlblcc** [comment]
I'm not sure we need to handle this object at all. AFAIK, this is always auto-generated by ScienceBase. We can output the onlineResource in the writer using the resource's ScienceBase identifier, if one is available.

**Comment by stansmith907** [comment]
Good point.  I was reading this as the next and previous were generated depending on user navigation, but the actual link may be generated as well.

**Comment by stansmith907** [comment]
The entire link{} object is auto generated.  We will not need to read or write this section.
