### ISSUE TITLE
sbJson 2.0 provenance

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdTranslator#61]
Mapping of sbJson provenance to mdTranslator internal data structure:
- [x] reader complete
- [x] writer complete

````json
"provenance":
{
    "annotation":"Provenance1",
    "dataSouce":"Input directly",
    "dateCreated":"2015-11-09T19:02:45Z",
    "lastUpdated":"2015-11-09T19:02:45Z",
    "lastUpdatedBy":"abc@usgs.gov",
    "createdBy":"abc@usgs.gov",
    "fileProcess": "???",
    "linkProcess": "???"
}
````
Definition... 
 * dataSource: Who/what created the metadata record

Set to 'generated using ADIwg mdTranslator 2.0.0'
 * dateCreated: The date and time the item was created.

Map to metadata metadataInfo metadataDate: 
[schema][metadata][metadataInfo][metadataDate][n].date
[view mdTools](http://mdtools.adiwg.org/#viewer-page?v=2-0-5-0-0)
[schema][metadata][metadataInfo][metadataDate][n].dateType
[view mdTools](http://mdtools.adiwg.org/#viewer-page?v=2-0-5-0-1)

 * lastUpdated: The date and time the item was last updated.
Map to metadata metadataInfo metadataDate: 
[schema][metadata][metadataInfo][metadataDate][n].date
[view mdTools](http://mdtools.adiwg.org/#viewer-page?v=2-0-5-0-0)
[schema][metadata][metadataInfo][metadataDate][n].dateType
[view mdTools](http://mdtools.adiwg.org/#viewer-page?v=2-0-5-0-1)

* createdBy: The person or organization who created the item.
Reading sbJson: ignore
Writing sbJson:
[schema][metadata][metadataInfo][metadatacontact][n].role when in list 
[ originator author resourceProvider coAuthor ].  All [party][contactId] > [contact][n][name] will be concatenated. 
[view mdTools](http://mdtools.adiwg.org/#viewer-page?v=2-0-4-0-0)

* lastUpdatedBy: The last person or organization to update the item.
Reading sbJson: ignore
Writing sbJson:
[schema][metadata][metadataInfo][metadatacontact][n].role when in list 
[ custodian ].  All [party][contactId] > [contact][n][name] will be concatenated. 
[view mdTools](http://mdtools.adiwg.org/#viewer-page?v=2-0-4-0-0)

* Not Mapped:
  * annotation
  * fileProcess
  * linkProcess
___
Mapping to mdTranslator from sbJson
````ruby
def newBase
   {
      metadata: {
         metadataInfo: {
            metadataIdentifier: {},
            parentMetadata: {},
            defaultMetadataLocale: {},
            otherMetadataLocales: [],
            metadataContacts: [],
            metadataDates: [
               {
                  date: '2015-11-09T19:02:45Z',
                  dateResolution: 'YMDhmsZ',
                  dateType: 'creation',
                  description: nil
               },
               {
                  date: '2015-11-09T19:02:45Z',
                  dateResolution: 'YMDhmsZ',
                  dateType: 'lastUpdate',
                  description: nil
               }
            ],
            metadataLinkages: [],
            metadataMaintenance: {},
            alternateMetadataReferences: [],
            metadataStatus: nil,
            extensions: []
         }
      }
   }
end
````

**Comment by stansmith907** [comment]
The *createdBy* and *lastUpdatedBy* roles are converted to ISO standard roles 'originator' and 'editor' in 'responsibleParty' respectively.  The ScienceBase names for these roles are preserved in 'contact[n].contactType' providing an additional means of linking.

**Comment by jlblcc** [comment]
I think the `provenance` object is referring to the ScienceBase item _record_, not the resource (all the sbJSON examples I've seen indicate this). Therefore the lineage mapping wouldn't apply. The `dateCreated` and `lastUpdated` properties could be mapped to [metadata > metadataInfo > metadataDate](http://mdtools.adiwg.org/#viewer-page?v=2-0-5).

**Comment by stansmith907** [comment]
Well, then that was a big waste of time.  I guess I need to stop thinking of sbJson as metadata about the resource - item.

**Comment by jlblcc** [comment]
Sorry. The definition in the docs is confusing. It indicates that it is akin to lineage, but I've never seen it used that way. 

sbJSON _is_ about the resource - some of it anyway. It's not super clear what's what from just looking at the raw JSON though.

**Comment by stansmith907** [comment]
I guess we should try and get some clarification from Lei Ann.

**Comment by stansmith907** [comment]
These are about the metadata more than the record.

Capture the creationDate, updateDate,
dateSource = 'generated using ADIwg mdTranslator 2.0.0'
createdBy = use metadataContact, email > name > organization

ignore other fields

**Comment by stansmith907** [comment]
What 'role' in 'metadataContact' 'responsibility' should we use to identify createdBy and lastUpdatedBy elements? Several could work createdBy but none are really good matches for lastUpdatedBy.  Unless we want to add another code to the list we could just not support lastUpdatedBy.  Any strong feelings?
