### ISSUE TITLE
sbJson 2.0 materialRequestInstructions

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdTranslator#62]
Mapping of sbJson materialRequestInstructions to mdTranslator internal data structure:
- [x] reader complete
- [x] writer complete

````json
{
    "materialRequestInstructions":"Material Request Instructions"
}
````
Definition: Material Request Instructions may include information about obtaining access to items, information, or physical samples (such as geologic specimens) that may not be available online. Information may include phone numbers, addresses, websites links, and office hours.
 * Map to metadata distributorInfo distributor orderProcess: 
[schema][metadata][distributorInfo][n][distributor][n][orderProcess][n].orderingInstructions
[view mdTools](http://mdtools.adiwg.org/#viewer-page?v=2-3-0-1-0-1-0-2)
[schema][metadata][distributorInfo][n][distributor][n][contact].roleName
[view mdTools](http://mdtools.adiwg.org/#viewer-page?v=2-3-0-1-0-0-0)
[schema][metadata][distributorInfo][n][distributor][n][contact][parties][n].contactId
[schema][metadata][distributorInfo][n][distributor][n][contact][parties][n].contactType
[view mdTools](http://mdtools.adiwg.org/#viewer-page?v=2-3-0-1-0-0-2-0-0)
[schema][contacts][n].contactId
[view mdTools](http://mdtools.adiwg.org/#viewer-page?v=1-0-0)
[schema][contacts][n].isOrganization
[view mdTools](http://mdtools.adiwg.org/#viewer-page?v=1-0-1)
[schema][contacts][n].name
[view mdTools](http://mdtools.adiwg.org/#viewer-page?v=1-0-2)
[schema][contacts][n].contactType
[view mdTools](http://mdtools.adiwg.org/#viewer-page?v=1-0-12)
___
Mapping to mdTranslator
````ruby
   def newBase
      intObj = {
         contacts: [
            {
               contactId: 'CID001',
               isOrganization: false,
               name: 'US Geological Survey ScienceBase',
               positionName: nil,
               memberOfOrgs: [],
               logos: [],
               phones: [],
               addresses: [],
               eMailList: [],
               onlineResources: [],
               hoursOfService: [],
               contactInstructions: nil,
               contactType: 'materialRequestInstructions'
            }
         ],
         metadata: {
            distributorInfo: [
               description: nil,
               distributor: [
                  contact: {
                     roleName: 'distributor',
                     roleExtents: [],
                     parties: [
                        {
                           contactId: 'CID001',
                           contactIndex: 0,
                           contactType: 'ScienceBase',
                           organizationMembers: []
                        }
                     ]
                  },
                  orderProcess: [
                     {
                        fees: nil,
                        plannedAvailability: {},
                        orderingInstructions: 'Material Request Instructions',
                        turnaround: nil
                     }
                  ],
                  transferOptions: []
               ]

            ],
         }
      }
   end
````
Translation to mdJson
````json
{
   "contact": [
      {
         "contactId": "CID001",
         "isOrganization": false,
         "name": "abc@usgs.gov",
         "contactType": "materialRequestInstructions"
      }
   ],
   "metadata": {
      "resourceDistribution": [
         {
            "description": "",
            "distributor": [
               {
                  "contact": {
                     "role": "distributor",
                     "party": [
                        {
                           "contactId": "CID001"
                        }
                     ]
                  },
                  "orderProcess": [
                     {
                        "orderingInstructions": "Material Request Instructions"
                     }
                  ]
               }
            ]
         }
      ]
   }
}
````

**Comment by stansmith907** [comment]
The role of 'distributor' is an ISO role assigned to 'distributor'. The ScienceBase names for this roles is preserved in 'contact[n].contactType' providing an additional means of linking.

**Comment by jlblcc** [comment]
Might want to create a default contact in the reader for ScienceBase, see [the current reader](https://github.com/adiwg/mdTranslator/blob/v1.4.0.beta14/lib/adiwg/mdtranslator/readers/sbJson/modules_v0/module_contacts.rb#L103). Although, it would be better to set the contactId to an UUID.

**Comment by stansmith907** [comment]
Setting a default contact is a good idea.  I know you would prefer a UUID.  Both UUID and an incremental ID have their problems.

**Comment by jlblcc** [comment]
In either case, we'll have to set some kind of `internal` property in the editor cause we don't want folks messing with it. We'll need something's that guaranteed to be unique. OR we can add a `namespace` property to the contact object. Maybe we should do that anyway, it could help with resolving conflicts down the line. We can also use that to hide stuff in the editor.

**Comment by stansmith907** [comment]
Of course we want people to add and modify contact details.  But locking the contact ID may be a good idea.  What I've often done in the past is use a UUID (or other surrogate) for the database ID and keep it hidden, then provide a visible, simple ID for users to play with.  But locking may be our best approach here as we get in difficulty maintaining IDs that have been used in responsibleParty blocks throughout the metadata.  If we do lock changing of the contactId after the initial record has been saved we wouldn't need to do anything fancy, just make the field inactive on the edit component.

**Comment by jlblcc** [comment]
I meant we don't want folks to change the default contacts. I don't want them to be editable at all. They're immutable(except by us). No one needs to change the ScienceBase reference contact.

What do you think about adding namespace to contact?

**Comment by stansmith907** [comment]
I don't see a need for namespace on contact.  We have some many other qualifiers in names and associated contact IDs.  

True there may be a few system added contacts that should not be tampered with by users.

What do you think about locking the contact ID?

**Comment by stansmith907** [comment]
Fill the contact party with contacts from contact type of 'materialRequestor' if none 'distributor' then if none 'ScienceBase'.
