### ISSUE TITLE
sbJson 2.0 parentId

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdTranslator#63]
Mapping of sbJson parentId to mdTranslator internal data structure:
- [x] reader complete
- [x] writer complete

````json
{
    "parentId":"4f46607504a61aa9773f463d""
}
````
Definition: The unique ScienceBase id of the parent of this item. This is a string. This is one of two required fields in creating a new item, the other field is title.
 * Map to metadata metadataInfo parentMetadata identifier: 
[schema][metadata][metadataInfo][parentMetadata][identifiers][n].identifier
[view mdTools](http://mdtools.adiwg.org/#viewer-page?v=2-0-1-6-0-0)
[schema][metadata][metadataInfo][parentMetadata][identifiers][n].namespace
[view mdTools](http://mdtools.adiwg.org/#viewer-page?v=2-0-1-6-0-1)
[schema][metadata][metadataInfo][parentMetadata].title
[view mdTools](http://mdtools.adiwg.org/#viewer-page?v=2-0-1-0)
___
Mapping to mdTranslator
````ruby
   def newBase
      intObj = {
         metadata: {
            metadataInfo: {
               parentMetadata: {
                  title: 'USGS ScienceBase parent identifier',
                  alternateTitles: [],
                  dates: [],
                  edition: nil,
                  responsibleParties: [],
                  presentationForms: [],
                  identifiers: [
                     {
                        identifier: '4f46607504a61aa9773f463d',
                        namespace: 'gov.sciencebase.catalog',
                        version: nil,
                        description: nil,
                        citation: {}
                     }
                  ],
                  series: {},
                  otherDetails: [],
                  onlineResources: [],
                  browseGraphics: []
               }
            }
         }
      }
   end
````
Translation to mdJson
````json
{
   "metadata": {
      "metadataInfo": {
         "parentMetadata": {
            "title": "USGS ScienceBase parent identifier",
            "identifier": [
               {
                  "identifier": "4f46607504a61aa9773f463d",
                  "nameSpace": "gov.sciencebase.catalog"
               }
            ]
         }
      }
   }
}
````

**Comment by jlblcc** [comment]
Note that the `title` here is only provided as an example. It may be any character string. The writer will need to search for the first identifier with namespace = `gov.sciencebase.catalog`.

**Comment by stansmith907** [comment]
Actually, I inserted the title.  I assume 'gov.sciencebase.catelog' namespace will be multiply occurring.  I'm not sure what we need to search?  `parentMetadata` is in its own tag.  Which would have been obvious if I had not messed up the mdJson example above - fixed now :).

**Comment by jlblcc** [comment]
Each item in SB can only have one parent(AFAIK). So an identifier with `"namespace": "gov.sciencebase.catalog"` should only appear once in the `parentMetadata > identifier` array. So we just need to search until we find one.

**Comment by stansmith907** [comment]
Ahh, you thinking we could end up with multiple identifiers?  I suppose we could if someone were to extend the record.

**Comment by jlblcc** [comment]
I'm sure we'll end up with all kinds of strange and wonderful things. :grimacing:
