### ISSUE TITLE
sbJson 2.0 contacts

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdTranslator#64]
Mapping of sbJson contacts to mdTranslator internal data structure:
- [x] reader complete
- [x] writer complete

````json
{
   "contacts": [
      {
         "name": "Robert N Prescott",
         "oldPartyId": 58818,
         "type": "Distributor",
         "sourceId": "asdf",
         "contactType": "person",
         "organizationsPerson": "usgs",
         "ttyPhone": "123-123-1234",
         "hours": "8-4",
         "instructions": "test",
         "email": "rprescott@usgs.gov",
         "active": true,
         "jobTitle": "Computer Programmer",
         "personalTitle": "test",
         "firstName": "Robert",
         "middleName": "N",
         "lastName": "Prescott",
         "note": "note",
         "aliases": [
            "VOLCANO HAZARDS TEAM",
            "VOLCANO SCIENCE CENTER"
         ],
         "fbmsCodes": [
            "GGWAWC0000"
         ],
         "logoUrl": "http://my.usgs.gov/static-cache/images/dataOwner/v1/logosMed/USGSLogo.gif",
         "smallLogoUrl": "http://my.usgs.gov/static-cache/images/dataOwner/v1/logosSmall/USGSLogo.gif",
         "organization": {
            "displayText": "Fort Collins Science Center"
         },
         "primaryLocation": {
            "see": "sbJson 2.0 primaryLocation"
         }
      }
   ]
}
````
Definition: The contacts of an item. This is an collection of basic typed contact objects, which have the fields: type, name, highlighted.

Mapping...
 * new contact
[schema][contacts][n].contactId
 * name: The name of the contact.
Map to contacts name
[schema][contacts][n].name
[view mdTools](http://mdtools.adiwg.org/#viewer-page?v=1-0-2)
 * type: An editable type to describe the person or organization.
Map to contacts contactType
[schema][contacts][n].contactType
[view mdTools](http://mdtools.adiwg.org/#viewer-page?v=1-0-12)
 * contactType: The type of contact, always "person" or "organization"
Map to contacts isOrganization
[schema][contacts][n].isOrganization
[view mdTools](http://mdtools.adiwg.org/#viewer-page?v=1-0-1)
 * ttyPhone: (none)
Map to contacts phones
[schema][contacts][n].[phones][n].phoneNumber
[view mdTools](http://mdtools.adiwg.org/#viewer-page?v=1-0-6-0-1)
[schema][contacts][n].[phones][n][phoneServiceTypes][n]
[view mdTools](http://mdtools.adiwg.org/#viewer-page?v=1-0-6-0-2)
 * hour: (none)
Map to contacts hoursOfService
[schema][contacts][n].hoursOfService
[view mdTools](http://mdtools.adiwg.org/#viewer-page?v=1-0-10)
 * instructions: (none)
Map to contacts contactInstructions
[schema][contacts][n].contactInstructions
[view mdTools](http://mdtools.adiwg.org/#viewer-page?v=1-0-11)
 * email: The email address of a person. Not included in organizations
Map to contacts eMailList
[schema][contacts][n][eMailList][n]
[view mdTools](http://mdtools.adiwg.org/#viewer-page?v=1-0-8-0)
 * jobTitle: (none)
Map to contacts positionName
[schema][contacts][n].positionName
[view mdTools](http://mdtools.adiwg.org/#viewer-page?v=1-0-3)
 * organization.displayText: (none)
Map to new contact 
[schema][contacts][n+1].contactId
[schema][contacts][n+1].name
[schema][contacts][n+1].isOrganization = true
[view mdTools](http://mdtools.adiwg.org/#viewer-page?v=1-0-2)
 * logoUrl: (none)
[schema][contacts][n].[logos][n].graphicName
[view mdTools](http://mdtools.adiwg.org/#viewer-page?v=1-0-5-0-0)
[schema][contacts][n].[logos][n].[graphicURI][n].uri
[view mdTools](http://mdtools.adiwg.org/#viewer-page?v=1-0-5-0-4-0-0)
 * smallLogoUrl: (none)
Map to contacts logos
[schema][contacts][n].[logos][n].graphicName
[view mdTools](http://mdtools.adiwg.org/#viewer-page?v=1-0-5-0-0)
[schema][contacts][n].[logos][n].[graphicURI][n].uri
[view mdTools](http://mdtools.adiwg.org/#viewer-page?v=1-0-5-0-4-0-0)

Not Mapped...
 * oldPartyId
 * sourceId
 * organizationsPerson
 * active
 * personalTitle
 * firstName
 * middleName
 * lastName
 * aliases
 * fbmsCodes
 * note
___
Mapping to mdTranslator
````ruby
   def newBase
      intObj = {
         contacts: [
            {
               contactId: 'CID001',
               isOrganization: false,
               name: 'Robert N Prescott',
               positionName: 'Computer Programmer',
               memberOfOrgs: ['CID002'],
               logos: [
                  {
                     graphicName: 'logoUrl',
                     graphicDescription: nil,
                     graphicType: nil,
                     graphicConstraints: [],
                     graphicURI: [
                        {
                           olResURI: 'http://my.usgs.gov/static-cache/images/dataOwner/v1/logosMed/USGSLogo.gif',
                           olResProtocol: nil,
                           olResName: nil,
                           olResDesc: nil,
                           olResFunction: nil
                        }
                     ]
                  },
                  {
                     graphicName: 'smallLogoUrl',
                     graphicURI: [
                        {
                           olResURI: 'http://my.usgs.gov/static-cache/images/dataOwner/v1/logosSmall/USGSLogo.gif',
                        }
                     ]
                  },
               ],
               phones: [
                  {
                     phoneName: nil,
                     phoneNumber: '123-123-1234',
                     phoneServiceTypes: ['tty']
                  }
               ],
               addresses: [],
               eMailList: ['rprescott@usgs.gov'],
               onlineResources: [],
               hoursOfService: ['8-4'],
               contactInstructions: 'test',
               contactType: 'Distributor'
            },
            {
               contactId: 'CID002',
               isOrganization: true,
               name: 'Fort Collins Science Center'
            }
         ]
      }
   end
````
Translation to mdJson
````json
{
   "contacts": [
      {
         "contactId": "CID001",
         "isOrganization": false,
         "name": "Robert N Prescott",
         "positionName": "Computer Programmer",
         "memberOfOrganization": ["CID002"],
         "logoGraphic": [
            {
               "fileName": "logoUrl",
               "fileUri": [
                  {
                     "uri": "http://my.usgs.gov/static-cache/images/dataOwner/v1/logosMed/USGSLogo.gif"
                  }
               ]
            },
            {
               "fileName": "smallLogoUrl",
               "fileUri": [
                  {
                     "uri": "http://my.usgs.gov/static-cache/images/dataOwner/v1/logosSmall/USGSLogo.gif"
                  }
               ]
            }
         ],
         "phone": [
            {
               "phoneNumber": "123-123-1234",
               "service": ["tty"]
            }
         ],
         "address": [],
         "electronicMailAddress": ["rprescott@usgs.gov"],
         "hoursOfService": ["8-4"],
         "contactInstructions": "test",
         "contactType": "Distributor"
      },
      {
         "contactId": "CID002",
         "isOrganization": true,
         "name": "Fort Collins Science Center"
      }
   ]
}
````

**Comment by jlblcc** [comment]
Just a note that the `contact -> type` mapping is one-way. The writer will need to determine the `type` by scanning the record for all instances of `party (contactId + role)`. Each unique instance of the `party` will need to be included in the sbJSON `contacts[ ]` with `type = role`.

**Comment by stansmith907** [comment]
I'm thinking no scanning will be necessary if a unique contact is created for each occurrence in sbJson.  I find a contact, I create one, and each has a unique ID so it can find its way back.  Otherwise we are making too many guesses about what contact to use in any situation.

**Comment by jlblcc** [comment]
When going from mdJSON to sbJSON, you'll have to put all the unique contacts into the sbJSON `contacts[ ]` array. To do that the contacts will need a `type` which can only be obtained from the `party` roles. It's a PITA, but the only way to grab them all is to scan for every instance of party. Unless we just use the contacts in the citation and call it good.

**Comment by stansmith907** [comment]
OK, you're talking about the `type` element specifically.  It is very likely that in mdJson a contact will be associated with several roles (types).  Since `contact < type` in sbJson is singular, are you thinking we need to create a new instance of contact in sbJson for each contact/role paring mdJson?

**Comment by jlblcc** [comment]
Exactly.

**Comment by stansmith907** [comment]
Not sure why `fbmsCodes` are associated with `contact`.  Any insight?  Not that we have a place for them anyway.

**Comment by jlblcc** [comment]
Nope. Might be related to agreement #s?
