### ISSUE TITLE
sbJson 2.0 tags

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdTranslator#69]
Mapping of sbJson tags to mdTranslator internal data structure:
- [x] reader complete
- [x] writer complete

````json
{
   "tags": [
      {
         "name":"Tag1"
      },
      {
         "name":"Tag2"
      },
      {
         "type":"Theme", 
         "scheme":"http://uri/to/vocab", 
         "name":"Happy Topic"
      }
   ]
}
````
Definition: The user specified tags or keywords of an item. These are used for grouping and searching items. It is a collection of tag objects, and the simplest representation of a tag has just one field, "name", the name the of the tag. Tags may also be terms from a vocabulary, with a type and scheme in addition to just the name.

Mapping...
 * name: The tag value.
Map to: [schema][metadata][resourceInfo][keywords][n][keywords][n].keyword
[view mdTools](http://mdtools.adiwg.org/#viewer-page?v=2-1-20-0-0-0-0)
 * type: Classifies the usage of the tag such as "Stratum", "Theme", "Label"
Map to: [schema][metadata][resourceInfo][keywords][n].keywordType
[view mdTools](http://mdtools.adiwg.org/#viewer-page?v=2-1-20-0-1)
 * scheme: Indicates what vocabulary the term came from.  The scheme is a resolvable URI when applicable similar the scheme in ATOM categories.
Map to: [schema][metadata][resourceInfo][keywords][n][thesaurus].title
[view mdTools](http://mdtools.adiwg.org/#viewer-page?v=2-1-20-0-2-0)
Map to: [schema][metadata][resourceInfo][keywords][n][thesaurus][onlineResources][n].olResURI
[view mdTools](http://mdtools.adiwg.org/#viewer-page?v=2-1-20-0-2-9-0-0)

___
Mapping to mdTranslator
````ruby
   def newBase
      intObj = {
         metadata: {
            resourceInfo: {
               keywords: [
                  {
                     keywords: [
                        {
                           keyword: 'Tag1'
                        }
                     ]
                  },
                  {
                     keywords: [
                        {
                           keyword: 'Tag2'
                        }
                     ]
                  },
                  {
                     keywords: [
                        {
                           keyword: 'Happy Topic',
                           keywordId: nil
                        }
                     ],
                     keywordType: 'Theme',
                     thesaurus: {
                        title: 'Thesaurus',
                        alternateTitles: [],
                        dates: [],
                        edition: nil,
                        responsibleParties: [],
                        presentationForms: [],
                        identifiers: [],
                        series: {},
                        otherDetails: [],
                        onlineResources: [
                           {
                              olResURI: 'http://uri/to/vocab'
                           }
                        ],
                        browseGraphics: []
                     }
                  }
               ]
            }
         }
      }
   end
````
Translation to mdJson
````json
{
   "metadata": {
      "resourceInfo": {
         "keyword": [
            {
               "keyword": [
                  {
                     "keyword": "Tag1"
                  }
               ]
            },
            {
               "keyword": [
                  {
                     "keyword": "Tag12"
                  }
               ]
            },
            {
               "keyword": [
                  {
                     "keyword": "Happy Topic"
                  }
               ],
               "keywordType": "Theme",
               "thesaurus": {
                  "title": "Thesaurus",
                  "onlineResource": [
                     {
                        "uri": "http://uri/to/vocab"
                     }
                  ]
               }
            }
         ]
      }
   }
}
````

**Comment by stansmith907** [comment]
The mapping is a bit verbose.  In sbJson the scheme (thesaurus) is associated with each keyword individually.  So there is no guarantee that one keyword comes from the same vocabulary as another.  Thus each keyword is placed in a separate keyword block.

I am also not sure that `tags` are always used as "keywords".  Is there some internal ScienceBase use for `tags'?

**Comment by stansmith907** [comment]
My impressions after discussing this topic in today's LCC ScienceBase Catalog Support meeting is:

1. Tags are user generated and not controlled - which fits the keyword model.  
2. Tags are not used to control any parts of the ScienceBase model or webpages; however, some subsequent systems may (and some do) use the tags to control their systems.  
3. Tags are single keywords.  Whatever is in the `name` element IS the search criteria; so combining keywords in lists is a bad idea.

With these clarifications I think it is safe to map tags to keywords.  Although there may be some unusual keywords.

**Comment by stansmith907** [comment]
I will try to group tags in the mdTranslator internal format.  

 * Gather all the tags with no `scheme` specified into one keyword group
 * Gather all tags of same `scheme` into their own keyword group.

I will break these back apart when writing to sbJson.

**Comment by jlblcc** [comment]
ISO 19115 Topic Categories should map to tags: 

```json
    {
      "type": "Label",
      "scheme": "ISO 19115 Topic Categories",
      "name": "geoscientificInformation"
    },
```

**Comment by stansmith907** [comment]
Scheme will be thesaurus URI if available, if not it will be un-themed. 

Reading sbJson check to see if scheme is "ISO 19115 Topic Categories" then this is Topic Category,
if scheme is URI create thesaurus with URI as onlineResource and title of "Unknown:

**Comment by stansmith907** [comment]
Reading: sbJson 'tags' look for 'scheme: 'adiwg.mdJson' (or something close) and may to 'resourceType' in mdJson. 

Writing: 
* all resourceTypes go to tags AND
* those that map directly to sbJson 'browseCategories' are written there as well.
