### ISSUE TITLE
sbJson 2.0 dates

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdTranslator#70]
Mapping of sbJson dates to mdTranslator internal data structure:
- [x] reader complete
- [x] writer complete

````json
{
   "dates": [
      {
         "type":"Publication",
         "dateString":"2012-01-01",
         "label": "Publication Date"
      },
      {
         "type":"Repository Created",
         "dateString":"2012",
         "label":"Repository Created"
      }
   ]
}
````
Definition: This can be the Start Date, the End Date, the date of publication or award, or any general date ("Info Date") associated with the record. There must be at least one date associated with any record.

Mapping...
 * type: The type of date.
Map to: [schema][metadata][resourceInfo][citation][dates][n].dateType
[view mdTools](http://mdtools.adiwg.org/#viewer-page?v=2-1-1-2-0-1)
 * dateString: The date. Note that this dateString must be in the format: YYYY, YYYY-MM, or YYYY-MM-DD or the date will not be saved.
Map to: [schema][metadata][resourceInfo][citation][dates][n].date
[view mdTools](http://mdtools.adiwg.org/#viewer-page?v=2-1-1-2-0-0)
 * label: The human readable label for the date type.
Map to: [schema][metadata][resourceInfo][citation][dates][n].description
[view mdTools](http://mdtools.adiwg.org/#viewer-page?v=2-1-1-2-0-2)

___
Mapping to mdTranslator
````ruby
   def newBase
      intObj = {
         metadata: {
            resourceInfo: {
               citation: {
                  title: nil,
                  alternateTitles: [],
                  dates: [
                     {
                        date: '2012-01-01',
                        dateResolution: 'YMD',
                        dateType: 'Publication',
                        description: 'Publication Date'
                     },
                     {
                        date: '2012',
                        dateResolution: 'Y',
                        dateType: 'Repository Created',
                        description: 'Repository Created'
                     }
                  ],
                  edition: nil,
                  responsibleParties: [],
                  presentationForms: [],
                  identifiers: [],
                  series: {},
                  otherDetails: [],
                  onlineResources: [],
                  browseGraphics: []
               }
            }
         }
      }
   end
````
Translation to mdJson
````json
{
   "metadata": {
      "resourceInfo": {
         "citation": {
            "date": [
               {
                  "date": "2012-01-01",
                  "dateType": "Publication",
                  "description": "Publication Date"
               },
               {
                  "date": "2012",
                  "dateType": "Repository Created",
                  "description": "Repository Created"
               }
            ]
         }
      }
   }
}
````

**Comment by jlblcc** [comment]
The dateType is a candidate for codelist translation. mdJSON to sbJSON will need codelist translation support to be compatible with SB CVLs.

**Comment by stansmith907** [comment]
Translation map for codes are on the arcticLcc drive.  Lei Ann mapped most of these out.

**Comment by jlblcc** [comment]
ScienceBase Date Vocab: https://www.sciencebase.gov/vocab/categories?max=1000&parentId=4f4e475de4b07f02db47ded1

**Comment by stansmith907** [comment]
Include resource timePeriod start and end dates in sbJson *dates*

**Comment by stansmith907** [comment]
For iso dateType(s) that do not map to scienceBase date types use *type* = 'Info' and place iso dateType in *label* element:
````json
{
   "dates": [
      {
         "type": "Info",
         "label": "expiry",
         "dateString": "1957"
      }
   ]
}
````
