### ISSUE TITLE
sbJson 2.0 facets

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdTranslator#73]
Not all facets are planned to be mapped to mdTranslator.  Please check the facets below that should be mapped to mdTranslator...

- [ ] ArcGIS REST Service Extension
- [ ] BASIS+ Extension
- [x] Budget Extension
- [x] Citation Extension
- [ ] Community Extension
- [ ] ESRI Map Package Extension
- [ ] ESRI Service Definition Extension
- [ ] Geology Extension
- [ ] GeoProcessing Service Extension
- [ ] Monitoring Protocol Extension
- [ ] NetCDF OPeNDAP Service Extension
- [ ] NGGDPP Collection Extension
- [ ] NGGDPP Item Extension
- [ ] OGC Web Service Extension
- [ ] Paleo Extension
- [x] Project Extension
- [ ] Raster Extension
- [ ] Shapefile Extension
- [ ] Stratigraphy Extension

**Comment by jlblcc** [comment]
Budget should be mapped to 'funding'. 

The project facet is used for resourceType=project. This is where status is mapped. There was some talk about adding a product facet for the same purpose. 

I'll let Lei Ann comment on the citation facet.

**Comment by jlblcc** [comment]
SB will add the following fields to the budget facet:

- recipient (string)
- matching (boolean)

**Comment by jlblcc** [comment]
Citation Extension should __only__ be used for 'publication' resources.
