### ISSUE TITLE
sbJson 2.0 spatial

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdTranslator#74]
Mapping of sbJson spatial to mdTranslator internal data structure:
- [x] reader complete
- [x] writer complete

````json
{
   "spatial": {
      "representationalPoint": [123,23],
      "representationalPointIsDerived": false,
      "boundingBox": {
         "maxY": 23.22,
         "maxX": 12.12,
         "minX": 23.21,
         "minY": 43
      }
   }
}
````
Definition: This is the spatial representation of the item.

Mapping...
 * representationalPoint: A collection of two points (saved as Doubles). The first value is latitude and must be within -180 & +180. The second value is the longitude and must be within -90 & 90.
Map to: [schema][metadata][resourceInfo][extents][n][geographicExtents][n][geographicElement][n][geographicElements][n].type = 'Feature'
[view mdTools](http://mdtools.adiwg.org/#viewer-page?v=2-1-15-0-1-0-3-0-1-0-1-2-0)
Map to: [schema][metadata][resourceInfo][extents][n][geographicExtents][n][geographicElement][n][geographicElements][n].id= 'representationalPoint'
[view mdTools](http://mdtools.adiwg.org/#viewer-page?v=2-1-15-0-1-0-3-0-1-0-1-2-3)
Map to: [schema][metadata][resourceInfo][extents][n][geographicExtents][n][geographicElement][n][geographicElements][n][geometryObject].type= 'Point'
[view mdTools](http://mdtools.adiwg.org/#viewer-page?v=2-1-15-0-1-0-3-0-1-0-1-2-1-0-1-0-0-0)
Map to: [schema][metadata][resourceInfo][extents][n][geographicExtents][n][geographicElement][n][geographicElements][n][geometryObject].coordinates
[view mdTools](http://mdtools.adiwg.org/#viewer-page?v=2-1-15-0-1-0-3-0-1-0-1-2-1-0-1-0-0-1)
 * representationalPointIsDerived: Whether or not the representational point is derived. This is generally false.
Map to: [schema][metadata][resourceInfo][extents][n][geographicExtents][n][geographicElement][n][geographicElements][n][properties].acquisitionMethod = 'notDerived'
[view mdTools](http://mdtools.adiwg.org/#viewer-page?v=2-1-15-0-1-0-3-0-1-0-1-2-1-0-1-0-0-1)
 * boundingBox: The bounding box of an item. The maxY, minY, maxX, minX represent the four corners of the bounding box.
Map to: **[schema][metadata][resourceInfo][extents][n][geographicExtents][n][geographicElement][n][geographicElements][n].bbox
[view mdTools](http://mdtools.adiwg.org/#viewer-page?v=2-1-15-0-1-0-3-0-1-0-0)

___
Mapping to mdTranslator
````ruby
   def newBase
      intObj = {
         metadata: {
            resourceInfo: {
               extents: [
                  {
                     description: nil,
                     geographicExtents: [
                        {
                           containsData: true,
                           identifier: {},
                           boundingBox: {},
                           geographicElement: [
                              {
                                 nativeGeoJson: [],
                                 geographicElements: [
                                    {
                                       type: 'Feature',
                                       id: 'representationalPoint',
                                       bbox: [12.12, 43, 23.21, 23.22],
                                       geometryObject: {
                                          type: 'Point',
                                          coordinates: [123, 23]
                                       },
                                       properties: {
                                          featureNames: [],
                                          description: nil,
                                          identifiers: [],
                                          featureScope: nil,
                                          acquisitionMethod: 'notDerived'
                                       },
                                       computedBbox: []
                                    }
                                 ],
                                 computedBbox: {}
                              }
                           ]
                        }
                     ],
                     temporalExtents: [],
                     verticalExtents: []
                  }
               ]
            }
         }
      }
   end
````
Translation to mdJson
````json
{
   "metadata": {
      "resourceInfo": {
         "extent": [
            {
               "geographicExtent": [
                  {
                     "containsData": true,
                     "identifier": {},
                     "boundingBox": {},
                     "geographicElement": [
                        {
                           "type": "Feature",
                           "id": "representationalPoint",
                           "bbox": [12.12, 43, 23.21, 23.22],
                           "geometry": {
                              "type": "Point",
                              "coordinates": [123, 23]
                           },
                           "properties": {
                              "featureName": [],
                              "description": "",
                              "includesData": true,
                              "temporalElement": {},
                              "verticalElement": [],
                              "identifier": [],
                              "featureScope": "",
                              "featureAcquisitionMethod": "notDerived"
                           }
                        }
                     ]
                  }
               ]
            }
         ]
      }
   }
}
````

**Comment by stansmith907** [comment]
Spatial objects in mdJson are encoded in the GeoJSON standard.  I have represented the `spatial` object as a single GeoJSON *Feature* class.  This translation can be seen in the 'Translation to mdJson' section above.  The same 'GeoJson' object will be inserted into the geographicElements's 'nativeGeoJson' object so that it can be used by other writers such as the html writer.

Since the derivation method is Boolean I coded the 'featureAcquisitionMethod' to be either 'derived' or 'notDerived'.

**Comment by stansmith907** [comment]
I need to know the order of the bounding box coordinates.  min and max are possibly ambiguous.  Is `maxX` the most East or West?  Is maxY always the most North regardless of hemisphere?

**Comment by jlblcc** [comment]
boundingBox should map to http://mdtools.adiwg.org/#viewer-page?v=1-0-5-0-3-2-2-0-1-0-2

**Comment by stansmith907** [comment]
mdJson has multiple extents and a computed bbox for each extent.  Compute a new bbox using all the computed bbox as geometries.  Use this as the sbJson spatial bbox.
Ignore representational point.
