### ISSUE TITLE
sbJson 2.0 budget facet

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdTranslator#77]
elements matching (Boolean) and recipient (string) are not yet in the sbJson schema.  We will carry these anyway.

**Comment by jlblcc** [comment]
Here's the latest budget facet example (subject to change):

```json
{    ...
    "annualBudgets": [{
        "fundingSources": [{
                "amount": 135332,
                "source": "US Bureau of Reclamation",
            },
            {
                "amount": 58470,
                "source": "Salt River Project",
                "match": true,
                "recipient": "Lei Ann Wilson"
            },
            {
                "amount": 78264,
                "source": "Northern Arizona University"
            }
        ],
        "totalFunds": 272066,
        "year": "2012"
    }]
    ...
}
```

**Comment by stansmith907** [comment]
Use fiscal federal year beginning October 1.
Use period endDateTime if available, startDateTime if not.

**Comment by stansmith907** [comment]
Recipient and source in sbJson are text and in mdJson contactId(s).  In the sbJson writer we just moved the contactId(s) into the sbJson text fields.  But in the sbJson reader the text will not be valid mdJson contactId(s).  Do we want to attempt to search the contact array for contact names matching the text? or ignore recipient and source?
