### ISSUE TITLE
sbJson 2.0 project facet

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdTranslator#78]
Only thing we are requiring at this time is the className and the status.

Can include other data in type/value pairs in parts object. 
If we want to retain shortAbstract it will need to be included in these type/value pairs.  

Suggested we not use projectProducts{}.

ScienceBase status codes Active and InProgress will both map to onGoing on read and onGoing will map to InProgress on write.

**Comment by jlblcc** [comment]
Status should also be written to a tag (type= Status, scheme=??). 

The SB vocab link: https://www.sciencebase.gov/vocab/vocabulary/50339906e4b068b9cdc5461e

**Comment by stansmith907** [comment]
Do not include status types that cannot be translated from ISO to sbJson.
