### ISSUE TITLE
sbJson 2.0 product

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdTranslator#79]
This will need to be designed by ArcticLCC and implemented by ScienceBase.  

Purpose is to hold the product status.

**Comment by jlblcc** [comment]
Status should be written to a tag instead(type= Status, scheme=??).

The SB vocab link: https://www.sciencebase.gov/vocab/vocabulary/50339906e4b068b9cdc5461e

**Comment by stansmith907** [comment]
All resources need to have 'status', not just projects.
Always write out even if ISO status does not translate to sbJson status.
