### ISSUE TITLE
sbJson 2.0 extents 

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdTranslator#82]
The ID comes from sbJson, example
````json
{
   "extents": [
      3106448,
      3106508,
      3106509
   ]
}
````
https://www.sciencebase.gov/catalog/item/52f2735ee4b0a6f0bd498c2f?format=json

https://www.sciencebase.gov/catalog/extent/2005798?format=geojson

The geoJson will come with it's own property set of elements.  These need to somehow be preserved.  Bundle them in an object on read, save in an element, expand and output again on write.

**Comment by jlblcc** [comment]
Dump GeoJSON to `root->geographicExtents[]`

**Comment by stansmith907** [comment]
ScienceBase only accepts GeoJSON type=Feature or FeatureCollection.  Convert each geographicExtent into a FeatureCollection.  
If the geographicExtent contains a FeatureCollection pass it to sbJson as a separate extent.
Convert GeometryCollection(s) to FeatureCollection(s)
