### ISSUE TITLE
sbJSON data.gov

### ISSUE THREAD

**Issue by jlblcc** [adiwg/mdTranslator#83]
For data.gov publishing, we need to create with a type and separate scheme values for each entity(LCC). 

For sbJson WRITER >>
mdTranslator internal 'metadataRepository' records...
````ruby
{
   metadataRepositories: [
      {
         repository: 'data.gov',
         citation: {
            title: 'Arctic LCC Data.gov',
            alternateTitles: [],
            dates: [],
            edition: nil,
            responsibleParties: [],
            presentationForms: [],
            identifiers: [
               {
                  identifier: '6f991cdb-6bf5-4f1d-a05b-4b8345455150',
                  namespace: nil,
                  version: nil,
                  description: nil,
                  citation: {}
               }
            ],
            series: {},
            otherDetails: [],
            onlineResources: [],
            browseGraphics: []
         },
         metadataStandard: 'FGDC'
      },
      {
         repository: 'DataOne',
         metadataStandard: 'iso19115_2'
      }
   ]
}
````
sbJson tags written from above mdTranslator internal records...
```json
"tags": [
   {
      "type": "Harvest Set",
      "name": "Arctic LCC Data.gov"
   }
]
```
For sbJson READER >>
Ignore tags of type: Harvest Set

**Comment by jlblcc** [comment]
We'll need to use [metadataRepository](http://mdtools.adiwg.org/#viewer-page?v=3-0) along with a contact from [metadataContact](http://mdtools.adiwg.org/#viewer-page?v=2-0-4) or maybe add a contact to  [metadataRepository](http://mdtools.adiwg.org/#viewer-page?v=3-0) itself.

**Comment by jlblcc** [comment]
```json
"metadataRepository":
 {
    "repository": "data.gov",
    "title": "Data.gov",
    "identifier": "Arctic LCC",
    "metadataStandard": "iso19115_2"
  }
```

**Comment by stansmith907** [comment]
Add a *citation* element to mdJson *metadataRepository*. 
Add *metadataRepository* tag to sbJson.
sbJson *metadataRepository* is populated with the first mdJson *metadataRepository[]* object with *repository* = 'data.gov'.

**Comment by jlblcc** [comment]
Example entry for LCC Science Catalog:

"metadataRepository":
 [{
    "repository": "scienceBase",
    "citiation" : {
      "title": "LCC Network Science Catalog"
     },
    "metadataStandard": "mdJson"
  }]

**Comment by jlblcc** [comment]
Got a bug in how the metadataRepositories are being translated to sbJSON. **Every** metadataRepository entry needs to translate into a "harvest set". Not just the "data.gov" entries.

See: https://github.com/adiwg/mdTranslator/blob/40dbd4a70fdf7a7cef4985a58648ef794a177c56/lib/adiwg/mdtranslator/writers/sbJson/sections/sbJson_tag.rb#L62

**Comment by stansmith907** [comment]
Every metadataRepository? Or every metadataRepository with a citation since we pull harvest tag name from citation.title/  Or should we pull tag name from repository if citation name not available?  However, that may lead to many duplicates over time, such as bunches of tag names of 'data.gov'.

**Comment by jlblcc** [comment]
Good point. We should only pass the ones with a title. It was also suggested that we might concatenate the repo code with the title for the harvest tag name, separated by a dash.  Probably not a bad idea since it would preserve the repo code in the tag.
